-- 02_opening.sql - the financial year, supplier masters, the opening balance sheet and the opening stock, all as on 1 April 2026.
begin;
select set_config('request.jwt.claims', json_build_object('sub', '2911a288-1727-4d24-869d-06ba96fc8ffa', 'role', 'authenticated')::text, false);
select set_config('demo.self_ok', (select allow_self_approval::text from purchase_settings where id = 1), false);
update purchase_settings set allow_self_approval = true where id = 1;
select set_config('demo.t0', clock_timestamp()::text, false);

select set_config('app.today', '2026-04-01', false);
select create_financial_year(2026);
-- Shopify pays out weekly
update channels set settlement_cycle = 'Weekly' where name like 'Shopify%';
select supplier_decide(supplier_save(null, '{"name":"Shree Ambika Textiles","gstin":"24AAKFS4418M1ZV","state_code":"24","payment_terms_days":30,"is_msme":true,"phone":"9825011401","email":"accounts@sat.example.com","address":"Plot 41, Ring Road Textile Market, Surat, Gujarat 395002","bank_name":"State Bank of India","ifsc":"SBIN0060128","account_number":"040100000000","account_holder":"Shree Ambika Textiles"}'::jsonb), 'approve');
select supplier_decide(supplier_save(null, '{"name":"Tiruppur Knit Fashions Pvt Ltd","gstin":"33AABCT7712K1ZB","state_code":"33","payment_terms_days":21,"is_msme":false,"phone":"9443022133","email":"accounts@tkf.example.com","address":"12/4 Kangeyam Road, Tiruppur, Tamil Nadu 641604","bank_name":"Indian Bank","ifsc":"IDIB000T045","account_number":"040107919003","account_holder":"Tiruppur Knit Fashions Pvt Ltd"}'::jsonb), 'approve');
select supplier_decide(supplier_save(null, '{"name":"Ludhiana Winter Wear Co","gstin":"03AAHFL2290P1Z1","state_code":"03","payment_terms_days":30,"is_msme":false,"phone":"9815066782","email":"accounts@lww.example.com","address":"B-77 Focal Point Phase V, Ludhiana, Punjab 141010","bank_name":"Punjab National Bank","ifsc":"PUNB0412300","account_number":"040115838006","account_holder":"Ludhiana Winter Wear Co"}'::jsonb), 'approve');
select supplier_decide(supplier_save(null, '{"name":"Krishna Denim Works","gstin":"24AADFK5531R1Z0","state_code":"24","payment_terms_days":45,"is_msme":true,"phone":"9825099410","email":"accounts@kdw.example.com","address":"Unit 9, Narol Industrial Estate, Ahmedabad, Gujarat 382405","bank_name":"Bank of Baroda","ifsc":"BARB0NAROLX","account_number":"040123757009","account_holder":"Krishna Denim Works"}'::jsonb), 'approve');
select supplier_decide(supplier_save(null, '{"name":"Rajdhani Shirting Mills","gstin":"27AAFCR8845E1Z3","state_code":"27","payment_terms_days":30,"is_msme":false,"phone":"9820012288","email":"accounts@rsm.example.com","address":"Gala 6, Dharavi Garment Hub, Mumbai, Maharashtra 400017","bank_name":"HDFC Bank","ifsc":"HDFC0000311","account_number":"040131676012","account_holder":"Rajdhani Shirting Mills"}'::jsonb), 'approve');
select supplier_decide(supplier_save(null, '{"name":"Little Stitch Garments","gstin":"24AAJFL1176Q1ZU","state_code":"24","payment_terms_days":15,"is_msme":true,"phone":"9712033655","email":"accounts@lsg.example.com","address":"Shop 18, Sachin GIDC Road, Surat, Gujarat 394230","bank_name":"Kotak Mahindra Bank","ifsc":"KKBK0002451","account_number":"040139595015","account_holder":"Little Stitch Garments"}'::jsonb), 'approve');
-- opening balance sheet: cash and bank, with the balancing figure in Retained Earnings (the opening stock is added to it below)
select import_run('ledger_opening', '[{"ledger":"Bank - ICICI Bank (7734)","debit":550000},{"ledger":"Bank - HDFC Bank (4821)","debit":250000},{"ledger":"Cash in Hand","debit":40000},{"ledger":"Retained Earnings","credit":840000}]'::jsonb, true,
  jsonb_build_object('financial_year', (select financial_year_id from accounting_periods order by start_date limit 1)), 'demo opening balances', null);
-- opening stock by warehouse (the stock-keeping side)
select record_inventory_movement(p.product_id, w.warehouse_id, 'initial_stock', v.q, 'opening', null) from (values
('BJNS-IND-1011Y','Surat Main Warehouse',6),
('BJNS-IND-45Y','Surat Main Warehouse',6),
('BJNS-IND-67Y','Surat Main Warehouse',6),
('BJNS-IND-89Y','Surat Main Warehouse',6),
('BKUR-CRM-45Y','Surat Main Warehouse',6),
('BKUR-CRM-67Y','Surat Main Warehouse',6),
('BKUR-CRM-89Y','Mumbai Fulfilment Center',3),
('BKUR-CRM-89Y','Surat Main Warehouse',6),
('BKUR-MUS-45Y','Mumbai Fulfilment Center',3),
('BKUR-MUS-45Y','Surat Main Warehouse',6),
('BKUR-MUS-67Y','Mumbai Fulfilment Center',3),
('BKUR-MUS-67Y','Surat Main Warehouse',6),
('BKUR-MUS-89Y','Surat Main Warehouse',6),
('BSHF-WHT-1011Y','Mumbai Fulfilment Center',3),
('BSHF-WHT-1011Y','Surat Main Warehouse',6),
('BSHF-WHT-45Y','Mumbai Fulfilment Center',3),
('BSHF-WHT-45Y','Surat Main Warehouse',6),
('BSHF-WHT-67Y','Surat Main Warehouse',6),
('BSHF-WHT-89Y','Mumbai Fulfilment Center',3),
('BSHF-WHT-89Y','Surat Main Warehouse',6),
('BSHT-GRY-45Y','Mumbai Fulfilment Center',3),
('BSHT-GRY-45Y','Surat Main Warehouse',6),
('BSHT-GRY-67Y','Mumbai Fulfilment Center',3),
('BSHT-GRY-67Y','Surat Main Warehouse',6),
('BSHT-GRY-89Y','Mumbai Fulfilment Center',3),
('BSHT-GRY-89Y','Surat Main Warehouse',6),
('BSHT-NVY-45Y','Mumbai Fulfilment Center',3),
('BSHT-NVY-45Y','Surat Main Warehouse',6),
('BSHT-NVY-67Y','Surat Main Warehouse',6),
('BSHT-NVY-89Y','Mumbai Fulfilment Center',3),
('BSHT-NVY-89Y','Surat Main Warehouse',6),
('BTEE-BLU-45Y','Surat Main Warehouse',6),
('BTEE-BLU-67Y','Mumbai Fulfilment Center',3),
('BTEE-BLU-67Y','Surat Main Warehouse',6),
('BTEE-BLU-89Y','Mumbai Fulfilment Center',3),
('BTEE-BLU-89Y','Surat Main Warehouse',6),
('BTEE-RED-45Y','Mumbai Fulfilment Center',3),
('BTEE-RED-45Y','Surat Main Warehouse',6),
('BTEE-RED-67Y','Mumbai Fulfilment Center',3),
('BTEE-RED-67Y','Surat Main Warehouse',6),
('BTEE-RED-89Y','Mumbai Fulfilment Center',3),
('BTEE-RED-89Y','Surat Main Warehouse',6),
('BTRK-BLK-1011Y','Mumbai Fulfilment Center',3),
('BTRK-BLK-1011Y','Surat Main Warehouse',6),
('BTRK-BLK-45Y','Mumbai Fulfilment Center',3),
('BTRK-BLK-45Y','Surat Main Warehouse',6),
('BTRK-BLK-67Y','Surat Main Warehouse',6),
('BTRK-BLK-89Y','Surat Main Warehouse',6),
('GFRK-LIL-45Y','Mumbai Fulfilment Center',3),
('GFRK-LIL-45Y','Surat Main Warehouse',6),
('GFRK-LIL-67Y','Mumbai Fulfilment Center',3),
('GFRK-LIL-67Y','Surat Main Warehouse',6),
('GFRK-LIL-89Y','Mumbai Fulfilment Center',3),
('GFRK-LIL-89Y','Surat Main Warehouse',6),
('GFRK-PNK-45Y','Surat Main Warehouse',6),
('GFRK-PNK-67Y','Mumbai Fulfilment Center',3),
('GFRK-PNK-67Y','Surat Main Warehouse',6),
('GFRK-PNK-89Y','Surat Main Warehouse',6),
('GJNS-IND-1011Y','Surat Main Warehouse',6),
('GJNS-IND-45Y','Mumbai Fulfilment Center',3),
('GJNS-IND-45Y','Surat Main Warehouse',6),
('GJNS-IND-67Y','Surat Main Warehouse',6),
('GJNS-IND-89Y','Surat Main Warehouse',6),
('GLEG-BLK-45Y','Mumbai Fulfilment Center',3),
('GLEG-BLK-45Y','Surat Main Warehouse',6),
('GLEG-BLK-67Y','Surat Main Warehouse',6),
('GLEG-BLK-89Y','Mumbai Fulfilment Center',3),
('GLEG-BLK-89Y','Surat Main Warehouse',6),
('GLEG-PNK-45Y','Mumbai Fulfilment Center',3),
('GLEG-PNK-45Y','Surat Main Warehouse',6),
('GLEG-PNK-67Y','Mumbai Fulfilment Center',3),
('GLEG-PNK-67Y','Surat Main Warehouse',6),
('GLEG-PNK-89Y','Mumbai Fulfilment Center',3),
('GLEG-PNK-89Y','Surat Main Warehouse',6),
('GLHG-RED-45Y','Surat Main Warehouse',6),
('GLHG-RED-67Y','Mumbai Fulfilment Center',3),
('GLHG-RED-67Y','Surat Main Warehouse',6),
('GLHG-RED-89Y','Surat Main Warehouse',6),
('GLHG-TEL-45Y','Mumbai Fulfilment Center',3),
('GLHG-TEL-45Y','Surat Main Warehouse',6),
('GLHG-TEL-67Y','Mumbai Fulfilment Center',3),
('GLHG-TEL-67Y','Surat Main Warehouse',6),
('GLHG-TEL-89Y','Mumbai Fulfilment Center',3),
('GLHG-TEL-89Y','Surat Main Warehouse',6),
('GNGT-PNK-1011Y','Mumbai Fulfilment Center',3),
('GNGT-PNK-1011Y','Surat Main Warehouse',6),
('GNGT-PNK-45Y','Surat Main Warehouse',6),
('GNGT-PNK-67Y','Mumbai Fulfilment Center',3),
('GNGT-PNK-67Y','Surat Main Warehouse',6),
('GNGT-PNK-89Y','Mumbai Fulfilment Center',3),
('GNGT-PNK-89Y','Surat Main Warehouse',6),
('GTOP-WHT-45Y','Mumbai Fulfilment Center',3),
('GTOP-WHT-45Y','Surat Main Warehouse',6),
('GTOP-WHT-67Y','Mumbai Fulfilment Center',3),
('GTOP-WHT-67Y','Surat Main Warehouse',6),
('GTOP-WHT-89Y','Mumbai Fulfilment Center',3),
('GTOP-WHT-89Y','Surat Main Warehouse',6),
('GTOP-YLW-45Y','Mumbai Fulfilment Center',3),
('GTOP-YLW-45Y','Surat Main Warehouse',6),
('GTOP-YLW-67Y','Mumbai Fulfilment Center',3),
('GTOP-YLW-67Y','Surat Main Warehouse',6),
('GTOP-YLW-89Y','Surat Main Warehouse',6),
('MBLZ-NVY-38','Mumbai Fulfilment Center',3),
('MBLZ-NVY-38','Surat Main Warehouse',6),
('MBLZ-NVY-40','Mumbai Fulfilment Center',3),
('MBLZ-NVY-40','Surat Main Warehouse',6),
('MBLZ-NVY-42','Surat Main Warehouse',6),
('MCHN-KHK-30','Mumbai Fulfilment Center',3),
('MCHN-KHK-30','Surat Main Warehouse',6),
('MCHN-KHK-32','Surat Main Warehouse',16),
('MCHN-KHK-34','Surat Main Warehouse',6),
('MCHN-OLV-30','Mumbai Fulfilment Center',3),
('MCHN-OLV-30','Surat Main Warehouse',6),
('MCHN-OLV-32','Surat Main Warehouse',6),
('MCHN-OLV-34','Mumbai Fulfilment Center',3),
('MCHN-OLV-34','Surat Main Warehouse',6),
('MHOD-BLK-L','Mumbai Fulfilment Center',3),
('MHOD-BLK-L','Surat Main Warehouse',6),
('MHOD-BLK-M','Mumbai Fulfilment Center',3),
('MHOD-BLK-M','Surat Main Warehouse',6),
('MHOD-BLK-XL','Mumbai Fulfilment Center',3),
('MHOD-BLK-XL','Surat Main Warehouse',6),
('MHOD-GRY-L','Mumbai Fulfilment Center',3),
('MHOD-GRY-L','Surat Main Warehouse',6),
('MHOD-GRY-M','Surat Main Warehouse',6),
('MHOD-GRY-XL','Surat Main Warehouse',6),
('MJNS-BLK-30','Mumbai Fulfilment Center',3),
('MJNS-BLK-30','Surat Main Warehouse',6),
('MJNS-BLK-32','Mumbai Fulfilment Center',3),
('MJNS-BLK-32','Surat Main Warehouse',6),
('MJNS-BLK-34','Mumbai Fulfilment Center',3),
('MJNS-BLK-34','Surat Main Warehouse',6),
('MJNS-IND-30','Mumbai Fulfilment Center',3),
('MJNS-IND-30','Surat Main Warehouse',6),
('MJNS-IND-32','Mumbai Fulfilment Center',3),
('MJNS-IND-32','Surat Main Warehouse',6),
('MJNS-IND-34','Mumbai Fulfilment Center',3),
('MJNS-IND-34','Surat Main Warehouse',6),
('MKUR-MUS-L','Surat Main Warehouse',6),
('MKUR-MUS-M','Mumbai Fulfilment Center',3),
('MKUR-MUS-M','Surat Main Warehouse',6),
('MKUR-MUS-XL','Surat Main Warehouse',6),
('MKUR-WHT-L','Mumbai Fulfilment Center',3),
('MKUR-WHT-L','Surat Main Warehouse',6),
('MKUR-WHT-M','Surat Main Warehouse',32),
('MKUR-WHT-XL','Mumbai Fulfilment Center',3),
('MKUR-WHT-XL','Surat Main Warehouse',6),
('MPOL-MRN-L','Surat Main Warehouse',6),
('MPOL-MRN-M','Surat Main Warehouse',6),
('MPOL-MRN-XL','Mumbai Fulfilment Center',3),
('MPOL-MRN-XL','Surat Main Warehouse',6),
('MPOL-NVY-L','Surat Main Warehouse',5),
('MPOL-NVY-M','Mumbai Fulfilment Center',3),
('MPOL-NVY-M','Surat Main Warehouse',6),
('MPOL-NVY-XL','Mumbai Fulfilment Center',3),
('MPOL-NVY-XL','Surat Main Warehouse',6),
('MSHC-GRN-L','Mumbai Fulfilment Center',3),
('MSHC-GRN-L','Surat Main Warehouse',6),
('MSHC-GRN-M','Mumbai Fulfilment Center',3),
('MSHC-GRN-M','Surat Main Warehouse',6),
('MSHC-GRN-XL','Surat Main Warehouse',6),
('MSHC-RED-L','Surat Main Warehouse',6),
('MSHC-RED-M','Surat Main Warehouse',6),
('MSHC-RED-XL','Mumbai Fulfilment Center',3),
('MSHC-RED-XL','Surat Main Warehouse',6),
('MSHF-SKY-L','Mumbai Fulfilment Center',3),
('MSHF-SKY-L','Surat Main Warehouse',6),
('MSHF-SKY-M','Mumbai Fulfilment Center',3),
('MSHF-SKY-M','Surat Main Warehouse',6),
('MSHF-SKY-XL','Mumbai Fulfilment Center',3),
('MSHF-SKY-XL','Surat Main Warehouse',6),
('MSHF-WHT-L','Mumbai Fulfilment Center',3),
('MSHF-WHT-L','Surat Main Warehouse',6),
('MSHF-WHT-M','Surat Main Warehouse',25),
('MSHF-WHT-XL','Mumbai Fulfilment Center',3),
('MSHF-WHT-XL','Surat Main Warehouse',6),
('MTEE-BLK-L','Mumbai Fulfilment Center',3),
('MTEE-BLK-L','Surat Main Warehouse',6),
('MTEE-BLK-M','Mumbai Fulfilment Center',3),
('MTEE-BLK-M','Surat Main Warehouse',6),
('MTEE-BLK-XL','Mumbai Fulfilment Center',3),
('MTEE-BLK-XL','Surat Main Warehouse',6),
('MTEE-WHT-L','Surat Main Warehouse',6),
('MTEE-WHT-M','Mumbai Fulfilment Center',3),
('MTEE-WHT-M','Surat Main Warehouse',6),
('MTEE-WHT-XL','Mumbai Fulfilment Center',3),
('MTEE-WHT-XL','Surat Main Warehouse',6),
('MTRK-BLK-L','Mumbai Fulfilment Center',3),
('MTRK-BLK-L','Surat Main Warehouse',6),
('MTRK-BLK-M','Mumbai Fulfilment Center',3),
('MTRK-BLK-M','Surat Main Warehouse',6),
('MTRK-BLK-XL','Surat Main Warehouse',6),
('WDRS-FLP-L','Mumbai Fulfilment Center',3),
('WDRS-FLP-L','Surat Main Warehouse',6),
('WDRS-FLP-M','Surat Main Warehouse',6),
('WDRS-FLP-S','Mumbai Fulfilment Center',3),
('WDRS-FLP-S','Surat Main Warehouse',6),
('WDRS-FLR-L','Mumbai Fulfilment Center',3),
('WDRS-FLR-L','Surat Main Warehouse',6),
('WDRS-FLR-M','Surat Main Warehouse',6),
('WDRS-FLR-S','Surat Main Warehouse',6),
('WDUP-GLD-FREE','Surat Main Warehouse',6),
('WDUP-SLV-FREE','Mumbai Fulfilment Center',3),
('WDUP-SLV-FREE','Surat Main Warehouse',6),
('WJKT-BLK-L','Surat Main Warehouse',6),
('WJKT-BLK-M','Surat Main Warehouse',6),
('WJKT-BLK-XL','Mumbai Fulfilment Center',3),
('WJKT-BLK-XL','Surat Main Warehouse',6),
('WJNS-BLK-28','Surat Main Warehouse',6),
('WJNS-BLK-30','Mumbai Fulfilment Center',3),
('WJNS-BLK-30','Surat Main Warehouse',6),
('WJNS-BLK-32','Mumbai Fulfilment Center',3),
('WJNS-BLK-32','Surat Main Warehouse',6),
('WJNS-IND-28','Mumbai Fulfilment Center',3),
('WJNS-IND-28','Surat Main Warehouse',6),
('WJNS-IND-30','Surat Main Warehouse',6),
('WJNS-IND-32','Surat Main Warehouse',6),
('WKRT-PNK-L','Mumbai Fulfilment Center',3),
('WKRT-PNK-L','Surat Main Warehouse',6),
('WKRT-PNK-M','Mumbai Fulfilment Center',3),
('WKRT-PNK-M','Surat Main Warehouse',6),
('WKRT-PNK-S','Mumbai Fulfilment Center',3),
('WKRT-PNK-S','Surat Main Warehouse',6),
('WKRT-PNK-XL','Mumbai Fulfilment Center',3),
('WKRT-PNK-XL','Surat Main Warehouse',6),
('WKRT-TEL-L','Mumbai Fulfilment Center',3),
('WKRT-TEL-L','Surat Main Warehouse',6),
('WKRT-TEL-M','Mumbai Fulfilment Center',3),
('WKRT-TEL-M','Surat Main Warehouse',6),
('WKRT-TEL-S','Surat Main Warehouse',14),
('WKRT-TEL-XL','Mumbai Fulfilment Center',3),
('WKRT-TEL-XL','Surat Main Warehouse',6),
('WLEG-BLK-L','Mumbai Fulfilment Center',3),
('WLEG-BLK-L','Surat Main Warehouse',6),
('WLEG-BLK-M','Mumbai Fulfilment Center',3),
('WLEG-BLK-M','Surat Main Warehouse',6),
('WLEG-MAR-L','Mumbai Fulfilment Center',3),
('WLEG-MAR-L','Surat Main Warehouse',6),
('WLEG-MAR-M','Mumbai Fulfilment Center',3),
('WLEG-MAR-M','Surat Main Warehouse',6),
('WLEG-NVY-L','Mumbai Fulfilment Center',3),
('WLEG-NVY-L','Surat Main Warehouse',6),
('WLEG-NVY-M','Mumbai Fulfilment Center',3),
('WLEG-NVY-M','Surat Main Warehouse',6),
('WLHG-MAG-L','Surat Main Warehouse',6),
('WLHG-MAG-M','Surat Main Warehouse',6),
('WLHG-RED-L','Mumbai Fulfilment Center',3),
('WLHG-RED-L','Surat Main Warehouse',6),
('WLHG-RED-M','Surat Main Warehouse',6),
('WPAL-WHT-L','Surat Main Warehouse',6),
('WPAL-WHT-M','Mumbai Fulfilment Center',3),
('WPAL-WHT-M','Surat Main Warehouse',6),
('WPAL-WHT-XL','Mumbai Fulfilment Center',3),
('WPAL-WHT-XL','Surat Main Warehouse',6),
('WPAL-YLW-L','Mumbai Fulfilment Center',3),
('WPAL-YLW-L','Surat Main Warehouse',6),
('WPAL-YLW-M','Mumbai Fulfilment Center',3),
('WPAL-YLW-M','Surat Main Warehouse',6),
('WPAL-YLW-XL','Mumbai Fulfilment Center',3),
('WPAL-YLW-XL','Surat Main Warehouse',6),
('WSAR-BLU-FREE','Mumbai Fulfilment Center',3),
('WSAR-BLU-FREE','Surat Main Warehouse',6),
('WSAR-GRN-FREE','Mumbai Fulfilment Center',3),
('WSAR-GRN-FREE','Surat Main Warehouse',6),
('WSAR-RED-FREE','Mumbai Fulfilment Center',3),
('WSAR-RED-FREE','Surat Main Warehouse',6),
('WTOP-PCH-L','Mumbai Fulfilment Center',3),
('WTOP-PCH-L','Surat Main Warehouse',6),
('WTOP-PCH-M','Mumbai Fulfilment Center',3),
('WTOP-PCH-M','Surat Main Warehouse',6),
('WTOP-PCH-S','Mumbai Fulfilment Center',3),
('WTOP-PCH-S','Surat Main Warehouse',6),
('WTOP-WHT-L','Mumbai Fulfilment Center',3),
('WTOP-WHT-L','Surat Main Warehouse',6),
('WTOP-WHT-M','Surat Main Warehouse',7),
('WTOP-WHT-S','Surat Main Warehouse',41)
) v(sku, wh, q) join products p on p.sku = v.sku join warehouses w on w.name = v.wh;
update inventory_transactions set created_at = '2026-04-01 09:00+05:30' where movement_type = 'initial_stock';
-- the accounting side of that stock: one entry at cost, against Retained Earnings. The stock rules switch on after this, so every later movement posts itself.
select acc_post_journal('2026-04-01', 'Opening stock at cost as on 1 April 2026', jsonb_build_array(
  jsonb_build_object('ledger_id', (select ledger_id from ledgers where name = 'Inventory - Stock-in-Trade'), 'debit', (select round(sum(b.quantity * p.cost_price), 2) from inventory_balances b join products p using (product_id)), 'credit', 0),
  jsonb_build_object('ledger_id', (select ledger_id from ledgers where name = 'Retained Earnings'), 'debit', 0, 'credit', (select round(sum(b.quantity * p.cost_price), 2) from inventory_balances b join products p using (product_id)))),
  'opening', null, 'posted', auth.uid());
select set_journal_pack_status('inventory_cogs', 'active');
update purchase_settings set allow_self_approval = coalesce(nullif(current_setting('demo.self_ok', true), '')::boolean, false) where id = 1;
select set_config('app.today', '', false);
commit;
