-- 0045: garment-retail catalogue (men, women, boys, girls), channel listings, October period.
-- Generated by supabase/seed/gen_garment_seed.py. GST: apparel <= Rs2,500/pc = 5%, above = 18%.
-- The 8 legacy non-garment SKUs are kept (orders/invoices reference them) but marked discontinued.

update products set status='discontinued' where sku in ('BAG-CNV','BOTL-750','EARBUD-PRO','MUG-350','SLEEVE-14','TS-BLK-M','TS-WHT-M','YOGA-6MM');

insert into accounting_periods (financial_year_id, period_name, start_date, end_date, status)
select 'FY2026-27','October 2026','2026-10-01','2026-10-31','open'
where not exists (select 1 from accounting_periods where start_date='2026-10-01');

with styles(ord,code,name,cat,brand,hsn,cost,price,cols,sizes) as (
  select row_number() over (), * from (values
('MTEE','Men Round Neck Cotton T-Shirt','Men - T-Shirts','UrbanLoom','610910',160,449,array[array['BLK','Black'],array['WHT','White']],array['M','L','XL']),
('MPOL','Men Pique Polo T-Shirt','Men - T-Shirts','UrbanLoom','610510',250,699,array[array['NVY','Navy'],array['MRN','Maroon']],array['M','L','XL']),
('MSHF','Men Formal Cotton Shirt','Men - Shirts','UrbanLoom','620520',340,999,array[array['WHT','White'],array['SKY','Sky Blue']],array['M','L','XL']),
('MSHC','Men Casual Checked Shirt','Men - Shirts','UrbanLoom','620520',320,899,array[array['RED','Red Check'],array['GRN','Green Check']],array['M','L','XL']),
('MJNS','Men Slim Fit Denim Jeans','Men - Bottomwear','UrbanLoom','620342',480,1399,array[array['IND','Indigo'],array['BLK','Black']],array['30','32','34']),
('MCHN','Men Stretch Chinos','Men - Bottomwear','UrbanLoom','620342',420,1199,array[array['KHK','Khaki'],array['OLV','Olive']],array['30','32','34']),
('MHOD','Men Fleece Hoodie','Men - Winterwear','UrbanLoom','611020',450,1299,array[array['GRY','Grey'],array['BLK','Black']],array['M','L','XL']),
('MKUR','Men Cotton Kurta','Men - Ethnic','UrbanLoom','621139',380,1099,array[array['MUS','Mustard'],array['WHT','White']],array['M','L','XL']),
('MBLZ','Men Tailored Blazer','Men - Formal','UrbanLoom','620311',1750,3799,array[array['NVY','Navy']],array['38','40','42']),
('MTRK','Men Track Pants','Men - Activewear','UrbanLoom','611030',230,649,array[array['BLK','Black']],array['M','L','XL']),
('WKRT','Women Printed Cotton Kurti','Women - Ethnic','Anaya','620440',290,849,array[array['PNK','Pink'],array['TEL','Teal']],array['S','M','L','XL']),
('WLEG','Women Churidar Leggings','Women - Bottomwear','Anaya','610469',120,349,array[array['BLK','Black'],array['MAR','Maroon'],array['NVY','Navy']],array['M','L']),
('WPAL','Women Cotton Palazzo','Women - Bottomwear','Anaya','620469',210,599,array[array['WHT','White'],array['YLW','Yellow']],array['M','L','XL']),
('WSAR','Women Surat Silk Saree','Women - Sarees','Anaya','540720',900,2199,array[array['RED','Red'],array['GRN','Green'],array['BLU','Royal Blue']],array['FREE']),
('WTOP','Women Casual Top','Women - Topwear','Anaya','610610',210,599,array[array['WHT','White'],array['PCH','Peach']],array['S','M','L']),
('WJNS','Women High-Rise Denim Jeans','Women - Bottomwear','Anaya','620462',460,1349,array[array['IND','Indigo'],array['BLK','Black']],array['28','30','32']),
('WDRS','Women Floral Midi Dress','Women - Dresses','Anaya','620442',520,1499,array[array['FLR','Floral Blue'],array['FLP','Floral Pink']],array['S','M','L']),
('WLHG','Women Bridal Lehenga Set','Women - Occasion','Anaya','620442',2600,5499,array[array['RED','Red'],array['MAG','Magenta']],array['M','L']),
('WDUP','Women Embroidered Dupatta','Women - Accessories','Anaya','621420',160,449,array[array['GLD','Gold'],array['SLV','Silver']],array['FREE']),
('WJKT','Women Quilted Winter Jacket','Women - Winterwear','Anaya','620230',1100,2699,array[array['BLK','Black']],array['M','L','XL']),
('BTEE','Boys Graphic T-Shirt','Boys - Topwear','Tiny Trends','610910',110,329,array[array['BLU','Blue'],array['RED','Red']],array['4-5Y','6-7Y','8-9Y']),
('BSHT','Boys Cotton Shorts','Boys - Bottomwear','Tiny Trends','610339',120,349,array[array['NVY','Navy'],array['GRY','Grey']],array['4-5Y','6-7Y','8-9Y']),
('BJNS','Boys Denim Jeans','Boys - Bottomwear','Tiny Trends','620342',290,799,array[array['IND','Indigo']],array['4-5Y','6-7Y','8-9Y','10-11Y']),
('BKUR','Boys Kurta Pyjama Set','Boys - Ethnic','Tiny Trends','621139',330,949,array[array['CRM','Cream'],array['MUS','Mustard']],array['4-5Y','6-7Y','8-9Y']),
('BTRK','Boys Tracksuit','Boys - Activewear','Tiny Trends','611220',360,999,array[array['BLK','Black']],array['4-5Y','6-7Y','8-9Y','10-11Y']),
('BSHF','Boys Party Shirt','Boys - Topwear','Tiny Trends','620520',210,599,array[array['WHT','White']],array['4-5Y','6-7Y','8-9Y','10-11Y']),
('GFRK','Girls Party Frock','Girls - Dresses','Tiny Trends','610442',260,749,array[array['PNK','Pink'],array['LIL','Lilac']],array['4-5Y','6-7Y','8-9Y']),
('GTOP','Girls Printed Top','Girls - Topwear','Tiny Trends','610610',120,349,array[array['YLW','Yellow'],array['WHT','White']],array['4-5Y','6-7Y','8-9Y']),
('GLEG','Girls Leggings','Girls - Bottomwear','Tiny Trends','610469',90,279,array[array['BLK','Black'],array['PNK','Pink']],array['4-5Y','6-7Y','8-9Y']),
('GLHG','Girls Lehenga Choli','Girls - Ethnic','Tiny Trends','620442',800,1999,array[array['RED','Red'],array['TEL','Teal']],array['4-5Y','6-7Y','8-9Y']),
('GJNS','Girls Denim Jeans','Girls - Bottomwear','Tiny Trends','620462',280,779,array[array['IND','Indigo']],array['4-5Y','6-7Y','8-9Y','10-11Y']),
('GNGT','Girls Night Suit Set','Girls - Nightwear','Tiny Trends','610830',190,549,array[array['PNK','Pink']],array['4-5Y','6-7Y','8-9Y','10-11Y'])
  ) t(code,name,cat,brand,hsn,cost,price,cols,sizes)
), exp as (
  select s.*, c.cc[1] ccode, c.cc[2] cname, c.ci, z.sz, z.si
  from styles s
  cross join lateral (select array[ (s.cols)[i][1], (s.cols)[i][2] ] cc, i ci from generate_subscripts(s.cols,1) i) c
  cross join lateral (select sz, si from unnest(s.sizes) with ordinality u(sz,si)) z
), numbered as (
  select *, row_number() over (order by ord, ci, si) n from exp
)
insert into products (company_id, sku, name, variant, barcode, hsn, gst_rate, brand, category, cost_price, packaging_cost, status)
select (select company_id from companies limit 1),
  code||'-'||ccode||'-'||replace(sz,'-',''), name||' - '||cname, cname||' / '||sz,
  b12||((10 - (select sum(substr(b12,g,1)::int * case when g%2=0 then 3 else 1 end) from generate_series(1,12) g) % 10) % 10)::text,
  hsn, case when price <= 2500 then 5 else 18 end, brand, cat, cost, case when cat like 'Men%' or cat like 'Women%' then 12 else 10 end,
  case when code||'-'||ccode||'-'||replace(sz,'-','') = any(array['MSHF-WHT-M','MKUR-WHT-M','WTOP-WHT-S']) then 'discontinued'
       when code||'-'||ccode||'-'||replace(sz,'-','') = any(array['MPOL-NVY-L','MCHN-KHK-32','WKRT-TEL-S','WDRS-FLR-M']) then 'inactive' else 'active' end
from (select *, '890'||lpad((4000000 + n*37)::text, 9, '0') b12 from numbered) x
on conflict (company_id, sku) do nothing;

-- channel listings: every SKU on Shopify; ~78% on Amazon, ~62% on Flipkart (deterministic). Non-active SKUs are inactive on marketplaces.
insert into channel_sku_map (product_id, channel_id, channel_sku, listing_id, status)
select p.product_id, c.channel_id,
  case c.type when 'd2c' then p.sku when 'marketplace' then (case when c.name like 'Amazon%' then 'AMZ-' else 'FK-' end)||p.sku end,
  case when c.type='d2c' then (7400000000000 + abs(hashtext(p.sku)))::text
       when c.name like 'Amazon%' then 'B0'||upper(substr(md5(p.sku||'amz'),1,8))
       else 'APR'||upper(substr(md5(p.sku||'fk'),1,13)) end,
  case when c.type<>'d2c' and p.status<>'active' then 'inactive' else 'active' end
from products p cross join channels c
where p.sku ~ '^[A-Z]+-[A-Z]+-' and p.sku not in ('BAG-CNV','BOTL-750','EARBUD-PRO','MUG-350','SLEEVE-14','TS-BLK-M','TS-WHT-M','YOGA-6MM')
  and (c.type='d2c' or (c.name like 'Amazon%' and abs(hashtext(p.sku||'a'))%100 < 78) or (c.name like 'Flipkart%' and abs(hashtext(p.sku||'f'))%100 < 62))
on conflict do nothing;
