-- 0046: garment demo transactions - opening stock, 72 orders across Shopify/Amazon/Flipkart, invoices (CGST+SGST vs IGST),
-- returns, RTOs, COD, settlements, claims, credit notes. Generated by supabase/seed/gen_garment_seed.py.
-- Runs as the Super Admin so the SECURITY DEFINER engine functions (post_sales_voucher, disposition_*,
-- reconcile_settlement, ...) execute their real posting logic rather than being bypassed.

select set_config('request.jwt.claims', json_build_object('sub','2911a288-1727-4d24-869d-06ba96fc8ffa','role','authenticated')::text, true);
-- (no role switch: the engine functions are SECURITY DEFINER and check auth.uid()'s role, so the real posting logic still runs)

-- orders
insert into orders (external_order_id, channel_id, order_date, customer_ref, payment_type, gross_amount, discount, tax_amount, net_amount, fulfilment_status, payment_status, ship_to_state)
values
('AMAZ-1110','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-02 10:12+05:30','Amit Sethi','prepaid',2197,89.8,105.36,2212.56,'delivered','paid','Gujarat'),
('AMAZ-1106','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-02 16:17+05:30','Anjali Verma','cod',2046,67.35,98.93,2077.58,'delivered','paid','Gujarat'),
('SHOP-1112','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-04 16:30+05:30','Kiran Naik','cod',2797,97.4,134.98,2834.58,'delivered','paid','Gujarat'),
('SHOP-1118','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-04 19:52+05:30','Vivek Singh','prepaid',1647,212.15,71.74,1506.59,'delivered','paid','Gujarat'),
('SHOP-1119','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-05 10:15+05:30','Tanvi Rana','cod',4693,434.4,212.93,4471.53,'delivered','paid','Gujarat'),
('SHOP-1114','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-05 10:47+05:30','Kavya Menon','cod',1898,59.9,91.9,1930.0,'delivered','paid','Gujarat'),
('FLIP-1118','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-05 13:33+05:30','Harsh Modi','prepaid',599,29.95,28.45,597.5,'delivered','paid','Gujarat'),
('AMAZ-1113','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-05 17:09+05:30','Tanvi Rana','prepaid',449,67.35,19.08,400.73,'delivered','paid','Gujarat'),
('FLIP-1117','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-05 18:12+05:30','Sejal Kapadia','prepaid',4796,474.65,216.07,4537.42,'delivered','paid','Rajasthan'),
('FLIP-1116','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-06 14:28+05:30','Sonal Parekh','prepaid',349,52.35,14.83,311.48,'delivered','paid','Gujarat'),
('SHOP-1113','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-06 14:37+05:30','Isha Gupta','cod',5499,549.9,890.84,5839.94,'delivered','paid','Gujarat'),
('FLIP-1114','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-08 10:38+05:30','Pooja Jain','prepaid',5997,359.75,948.52,6585.77,'delivered','paid','Gujarat'),
('SHOP-1132','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-08 12:15+05:30','Bhavna Solanki','prepaid',5846,499.7,267.31,5613.61,'shipped','refunded','Rajasthan'),
('SHOP-1122','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-08 12:54+05:30','Riya Shah','cod',449,0,22.45,471.45,'shipped','failed','Gujarat'),
('FLIP-1115','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-09 11:41+05:30','Rohit Iyer','cod',5096,334.75,238.06,4999.31,'delivered','paid','Maharashtra'),
('SHOP-1116','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-09 13:18+05:30','Rohit Iyer','cod',2947,347.15,130.0,2729.85,'delivered','paid','Gujarat'),
('SHOP-1130','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-09 14:54+05:30','Chirag Zaveri','prepaid',1047,104.7,47.11,989.41,'delivered','paid','Gujarat'),
('AMAZ-1116','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-10 10:25+05:30','Nidhi Agarwal','prepaid',9596,0,1467.54,11063.54,'delivered','paid','Tamil Nadu'),
('SHOP-1115','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-10 10:48+05:30','Rahul Bhatt','prepaid',5997,359.75,948.52,6585.77,'delivered','paid','Gujarat'),
('SHOP-1110','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-10 14:09+05:30','Harsh Modi','prepaid',1349,202.35,57.33,1203.98,'delivered','paid','Gujarat'),
('SHOP-1121','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-10 17:51+05:30','Nidhi Agarwal','cod',3797,0,189.85,3986.85,'delivered','paid','Gujarat'),
('FLIP-1104','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-10 19:37+05:30','Meghna Rao','prepaid',2747,0,137.35,2884.35,'delivered','paid','Delhi'),
('AMAZ-1109','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-10 19:52+05:30','Isha Gupta','prepaid',279,13.95,13.25,278.3,'delivered','paid','Maharashtra'),
('AMAZ-1114','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-11 12:28+05:30','Sonal Parekh','prepaid',3447,134.9,165.6,3477.7,'shipped','refunded','Gujarat'),
('FLIP-1110','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-12 12:42+05:30','Pratik Lad','prepaid',5499,0,989.82,6488.82,'delivered','paid','Rajasthan'),
('FLIP-1112','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-12 18:43+05:30','Anjali Verma','cod',2585,289.05,114.8,2410.75,'delivered','paid','Tamil Nadu'),
('AMAZ-1105','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-13 11:29+05:30','Riya Shah','prepaid',3799,379.9,615.44,4034.54,'delivered','paid','Delhi'),
('FLIP-1109','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-13 17:15+05:30','Manav Joshi','prepaid',3496,154.8,167.06,3508.26,'delivered','paid','Gujarat'),
('SHOP-1103','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-13 18:11+05:30','Chirag Zaveri','prepaid',1948,0,97.4,2045.4,'cancelled','refunded','Maharashtra'),
('SHOP-1131','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-13 19:00+05:30','Sonal Parekh','cod',5995,344.6,615.84,6266.24,'delivered','paid','Maharashtra'),
('AMAZ-1119','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-14 19:15+05:30','Rohit Iyer','prepaid',698,34.9,33.16,696.26,'delivered','paid','Madhya Pradesh'),
('FLIP-1106','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-15 19:52+05:30','Sonal Parekh','prepaid',2946,441.9,125.2,2629.3,'shipped','refunded','Uttar Pradesh'),
('AMAZ-1122','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-16 13:23+05:30','Isha Gupta','prepaid',2847,0,142.35,2989.35,'delivered','paid','Gujarat'),
('AMAZ-1115','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-16 17:25+05:30','Yash Vora','cod',779,0,38.95,817.95,'delivered','paid','Maharashtra'),
('AMAZ-1117','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-17 10:33+05:30','Tanvi Rana','prepaid',349,34.9,15.71,329.81,'cancelled','refunded','Gujarat'),
('FLIP-1111','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-17 18:55+05:30','Amit Sethi','cod',11144,84.9,1605.57,12664.67,'delivered','paid','Gujarat'),
('SHOP-1106','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-18 11:57+05:30','Aarav Mehta','prepaid',1498,59.9,71.9,1510.0,'delivered','paid','Gujarat'),
('FLIP-1113','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-18 16:02+05:30','Chirag Zaveri','cod',3696,299.6,169.81,3566.21,'delivered','paid','Maharashtra'),
('AMAZ-1111','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-18 18:21+05:30','Amit Sethi','cod',2598,269.8,116.41,2444.61,'delivered','paid','Gujarat'),
('AMAZ-1102','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-19 13:30+05:30','Nidhi Agarwal','prepaid',3846,477.0,168.45,3537.45,'delivered','paid','Gujarat'),
('AMAZ-1120','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-19 14:33+05:30','Kavya Menon','prepaid',1757,0,87.85,1844.85,'cancelled','refunded','Delhi'),
('SHOP-1108','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-19 18:04+05:30','Riya Shah','prepaid',3799,569.85,581.25,3810.4,'cancelled','refunded','Gujarat'),
('SHOP-1101','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-21 15:38+05:30','Tanvi Rana','prepaid',3597,489.6,155.37,3262.77,'shipped','refunded','Maharashtra'),
('SHOP-1107','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-21 17:12+05:30','Harsh Modi','cod',1999,199.9,89.95,1889.05,'delivered','paid','Delhi'),
('SHOP-1127','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-22 12:20+05:30','Foram Thakkar','prepaid',649,0,32.45,681.45,'delivered','paid','Gujarat'),
('SHOP-1120','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-23 13:47+05:30','Chirag Zaveri','prepaid',3395,199.9,159.75,3354.85,'shipped','paid','Gujarat'),
('AMAZ-1108','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-23 13:50+05:30','Pratik Lad','prepaid',1657,65.8,79.56,1670.76,'delivered','paid','Gujarat'),
('AMAZ-1118','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-23 19:02+05:30','Amit Sethi','prepaid',3445,252.0,159.65,3352.65,'shipped','refunded','Karnataka'),
('FLIP-1105','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-24 10:23+05:30','Sonal Parekh','prepaid',449,0,22.45,471.45,'shipped','paid','Gujarat'),
('SHOP-1104','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-24 13:09+05:30','Amit Sethi','cod',8692,499.55,409.62,8602.07,'delivered','paid','Delhi'),
('FLIP-1108','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-24 19:01+05:30','Jigar Chauhan','prepaid',3597,59.9,176.85,3713.95,'delivered','paid','Gujarat'),
('AMAZ-1101','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-24 19:37+05:30','Manav Joshi','prepaid',3296,359.7,146.82,3083.12,'shipped','paid','Maharashtra'),
('FLIP-1107','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-25 11:19+05:30','Kunal Desai','cod',2814,211.6,130.12,2732.52,'delivered','paid','Gujarat'),
('SHOP-1129','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-25 15:42+05:30','Anjali Verma','prepaid',8442,179.7,413.11,8675.41,'delivered','paid','Gujarat'),
('AMAZ-1104','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-25 15:51+05:30','Neha Patel','prepaid',19044,952.2,2941.97,21033.77,'shipped','paid','Delhi'),
('AMAZ-1121','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-26 11:19+05:30','Rohit Iyer','prepaid',3097,219.8,143.86,3021.06,'delivered','paid','West Bengal'),
('FLIP-1102','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-26 13:32+05:30','Tanvi Rana','prepaid',2427,89.9,116.85,2453.95,'shipped','paid','Delhi'),
('AMAZ-1107','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-28 17:30+05:30','Pooja Jain','prepaid',599,59.9,26.95,566.05,'shipped','paid','Gujarat'),
('AMAZ-1112','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-09-28 17:55+05:30','Chirag Zaveri','prepaid',8198,824.85,1327.17,8700.32,'processing','paid','Delhi'),
('SHOP-1105','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-29 10:04+05:30','Sejal Kapadia','cod',5595,334.65,263.02,5523.37,'processing','pending','Rajasthan'),
('FLIP-1101','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-29 13:00+05:30','Bhavna Solanki','prepaid',3806,116.85,184.46,3873.61,'pending','pending','Maharashtra'),
('SHOP-1109','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-29 18:59+05:30','Yash Vora','prepaid',2198,42.45,107.78,2263.33,'shipped','paid','Karnataka'),
('SHOP-1117','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-30 12:34+05:30','Sonal Parekh','prepaid',10745,69.95,1521.49,12196.54,'processing','paid','Gujarat'),
('SHOP-1128','91c52e15-376f-4a85-b900-10113f695ce3','2026-09-30 16:39+05:30','Harsh Modi','cod',14092,949.65,1546.09,14688.44,'processing','pending','Gujarat'),
('FLIP-1103','839765d6-e205-405d-af6c-3079174d2fd0','2026-09-30 18:55+05:30','Kiran Naik','prepaid',5848,274.95,957.78,6530.83,'processing','paid','Karnataka'),
('SHOP-1123','91c52e15-376f-4a85-b900-10113f695ce3','2026-10-01 12:41+05:30','Kiran Naik','cod',649,0,32.45,681.45,'pending','pending','Delhi'),
('SHOP-1124','91c52e15-376f-4a85-b900-10113f695ce3','2026-10-01 13:56+05:30','Kunal Desai','prepaid',6098,274.95,970.28,6793.33,'pending','pending','Gujarat'),
('SHOP-1125','91c52e15-376f-4a85-b900-10113f695ce3','2026-10-01 17:04+05:30','Mitul Dave','prepaid',1198,0,59.9,1257.9,'shipped','paid','Gujarat'),
('SHOP-1126','91c52e15-376f-4a85-b900-10113f695ce3','2026-10-02 10:16+05:30','Isha Gupta','prepaid',5194,89.9,255.21,5359.31,'processing','paid','Gujarat'),
('SHOP-1111','91c52e15-376f-4a85-b900-10113f695ce3','2026-10-03 10:53+05:30','Aarav Mehta','prepaid',2798,0,139.9,2937.9,'pending','pending','Gujarat'),
('AMAZ-1103','b9f37f58-411a-4b8e-a07f-69b3a302187e','2026-10-03 13:49+05:30','Manav Joshi','prepaid',899,44.95,42.7,896.75,'processing','paid','West Bengal'),
('SHOP-1102','91c52e15-376f-4a85-b900-10113f695ce3','2026-10-03 19:32+05:30','Rohit Iyer','cod',2447,127.3,115.98,2435.68,'pending','pending','Gujarat');

insert into order_lines (order_id, product_id, quantity, unit_price, discount, tax)
select o.order_id, p.product_id, v.q, v.up, v.d, v.t from (values
('AMAZ-1110','MHOD-GRY-M',1,1299,0,64.95),
('AMAZ-1110','MTEE-WHT-M',2,449,89.8,40.41),
('AMAZ-1106','MPOL-NVY-M',1,699,0,34.95),
('AMAZ-1106','MTEE-WHT-XL',3,449,67.35,63.98),
('SHOP-1112','WKRT-PNK-L',1,849,0,42.45),
('SHOP-1112','WPAL-WHT-L',1,599,29.95,28.45),
('SHOP-1112','WJNS-BLK-30',1,1349,67.45,64.08),
('SHOP-1118','GFRK-PNK-45Y',1,749,112.35,31.83),
('SHOP-1118','GTOP-YLW-89Y',1,349,17.45,16.58),
('SHOP-1118','GNGT-PNK-67Y',1,549,82.35,23.33),
('SHOP-1119','WTOP-PCH-M',2,599,179.7,50.91),
('SHOP-1119','WKRT-PNK-M',2,849,254.7,72.17),
('SHOP-1119','WPAL-YLW-L',3,599,0,89.85),
('SHOP-1114','WPAL-WHT-M',1,599,59.9,26.95),
('SHOP-1114','MHOD-GRY-M',1,1299,0,64.95),
('FLIP-1118','WPAL-YLW-XL',1,599,29.95,28.45),
('AMAZ-1113','WDUP-GLD-FREE',1,449,67.35,19.08),
('FLIP-1117','MJNS-BLK-34',2,1399,279.8,125.91),
('FLIP-1117','MHOD-GRY-L',1,1299,194.85,55.21),
('FLIP-1117','MPOL-MRN-XL',1,699,0,34.95),
('FLIP-1116','BSHT-NVY-67Y',1,349,52.35,14.83),
('SHOP-1113','WLHG-RED-L',1,5499,549.9,890.84),
('FLIP-1114','WTOP-PCH-L',1,599,89.85,25.46),
('FLIP-1114','WJKT-BLK-XL',2,2699,269.9,923.06),
('SHOP-1132','WPAL-YLW-XL',1,599,59.9,26.95),
('SHOP-1132','WKRT-PNK-L',1,849,0,42.45),
('SHOP-1132','WSAR-BLU-FREE',2,2199,439.8,197.91),
('SHOP-1122','MTEE-BLK-L',1,449,0,22.45),
('FLIP-1115','MCHN-KHK-30',2,1199,0,119.9),
('FLIP-1115','MJNS-BLK-32',1,1399,139.9,62.95),
('FLIP-1115','MHOD-GRY-M',1,1299,194.85,55.21),
('SHOP-1116','BTRK-BLK-67Y',2,999,299.7,84.92),
('SHOP-1116','BKUR-MUS-45Y',1,949,47.45,45.08),
('SHOP-1130','GTOP-YLW-89Y',1,349,0,17.45),
('SHOP-1130','GTOP-YLW-67Y',2,349,104.7,29.66),
('AMAZ-1116','MBLZ-NVY-40',2,3799,0,1367.64),
('AMAZ-1116','MSHF-WHT-XL',2,999,0,99.9),
('SHOP-1115','WJKT-BLK-M',2,2699,269.9,923.06),
('SHOP-1115','WPAL-WHT-M',1,599,89.85,25.46),
('SHOP-1110','WJNS-BLK-28',1,1349,202.35,57.33),
('SHOP-1121','MCHN-OLV-32',2,1199,0,119.9),
('SHOP-1121','MJNS-IND-34',1,1399,0,69.95),
('FLIP-1104','BKUR-MUS-45Y',1,949,0,47.45),
('FLIP-1104','MSHC-GRN-XL',2,899,0,89.9),
('AMAZ-1109','GLEG-BLK-67Y',1,279,13.95,13.25),
('AMAZ-1114','WDRS-FLP-L',1,1499,0,74.95),
('AMAZ-1114','WTOP-PCH-M',1,599,0,29.95),
('AMAZ-1114','WJNS-BLK-28',1,1349,134.9,60.7),
('FLIP-1110','WLHG-MAG-L',1,5499,0,989.82),
('FLIP-1112','BJNS-IND-45Y',2,799,239.7,67.92),
('FLIP-1112','BTEE-RED-67Y',1,329,49.35,13.98),
('FLIP-1112','BTEE-BLU-89Y',2,329,0,32.9),
('AMAZ-1105','MBLZ-NVY-40',1,3799,379.9,615.44),
('FLIP-1109','MPOL-MRN-L',1,699,104.85,29.71),
('FLIP-1109','MSHC-GRN-M',2,899,0,89.9),
('FLIP-1109','MSHF-SKY-M',1,999,49.95,47.45),
('SHOP-1103','BKUR-MUS-45Y',1,949,0,47.45),
('SHOP-1103','BTRK-BLK-89Y',1,999,0,49.95),
('SHOP-1131','WPAL-YLW-M',1,599,29.95,28.45),
('SHOP-1131','WJKT-BLK-M',1,2699,134.95,461.53),
('SHOP-1131','WPAL-WHT-XL',2,599,179.7,50.91),
('SHOP-1131','WDRS-FLP-M',1,1499,0,74.95),
('AMAZ-1119','WLEG-BLK-M',2,349,34.9,33.16),
('FLIP-1106','MPOL-MRN-XL',3,699,314.55,89.12),
('FLIP-1106','WKRT-PNK-S',1,849,127.35,36.08),
('AMAZ-1122','BKUR-MUS-89Y',3,949,0,142.35),
('AMAZ-1115','GJNS-IND-67Y',1,779,0,38.95),
('AMAZ-1117','BSHT-GRY-45Y',1,349,34.9,15.71),
('FLIP-1111','WJNS-BLK-32',1,1349,0,67.45),
('FLIP-1111','WJKT-BLK-M',3,2699,0,1457.46),
('FLIP-1111','WLEG-BLK-L',1,349,17.45,16.58),
('FLIP-1111','WJNS-BLK-30',1,1349,67.45,64.08),
('SHOP-1106','MSHC-RED-M',1,899,0,44.95),
('SHOP-1106','WPAL-WHT-XL',1,599,59.9,26.95),
('FLIP-1113','MSHC-RED-XL',1,899,89.9,40.45),
('FLIP-1113','MPOL-NVY-M',2,699,209.7,59.41),
('FLIP-1113','MJNS-BLK-34',1,1399,0,69.95),
('AMAZ-1111','MCHN-OLV-32',1,1199,59.95,56.95),
('AMAZ-1111','MJNS-IND-34',1,1399,209.85,59.46),
('AMAZ-1102','BTRK-BLK-45Y',1,999,49.95,47.45),
('AMAZ-1102','BKUR-CRM-89Y',3,949,427.05,121.0),
('AMAZ-1120','MCHN-OLV-30',1,1199,0,59.95),
('AMAZ-1120','GLEG-PNK-67Y',2,279,0,27.9),
('SHOP-1108','MBLZ-NVY-40',1,3799,569.85,581.25),
('SHOP-1101','MHOD-BLK-L',2,1299,389.7,110.42),
('SHOP-1101','MSHF-SKY-L',1,999,99.9,44.95),
('SHOP-1107','GLHG-RED-89Y',1,1999,199.9,89.95),
('SHOP-1127','MTRK-BLK-XL',1,649,0,32.45),
('SHOP-1120','GTOP-WHT-67Y',1,349,0,17.45),
('SHOP-1120','GLHG-TEL-45Y',1,1999,199.9,89.95),
('SHOP-1120','GTOP-YLW-45Y',3,349,0,52.35),
('AMAZ-1108','BTRK-BLK-89Y',1,999,0,49.95),
('AMAZ-1108','BTEE-BLU-67Y',2,329,65.8,29.61),
('AMAZ-1118','MTEE-BLK-XL',3,449,202.05,57.25),
('AMAZ-1118','MSHF-SKY-XL',1,999,49.95,47.45),
('AMAZ-1118','MKUR-MUS-L',1,1099,0,54.95),
('FLIP-1105','WDUP-SLV-FREE',1,449,0,22.45),
('SHOP-1104','MKUR-WHT-XL',2,1099,0,109.9),
('SHOP-1104','MHOD-GRY-M',1,1299,129.9,58.45),
('SHOP-1104','MKUR-WHT-L',2,1099,219.8,98.91),
('SHOP-1104','MSHF-SKY-M',3,999,149.85,142.36),
('FLIP-1108','WDRS-FLP-M',2,1499,0,149.9),
('FLIP-1108','WPAL-YLW-XL',1,599,59.9,26.95),
('AMAZ-1101','MCHN-OLV-34',2,1199,359.7,101.92),
('AMAZ-1101','MTEE-BLK-M',1,449,0,22.45),
('AMAZ-1101','MTEE-WHT-XL',1,449,0,22.45),
('FLIP-1107','GJNS-IND-1011Y',2,779,155.8,70.11),
('FLIP-1107','GLEG-PNK-89Y',2,279,55.8,25.11),
('FLIP-1107','GTOP-WHT-67Y',2,349,0,34.9),
('SHOP-1129','WSAR-RED-FREE',2,2199,0,219.9),
('SHOP-1129','WDUP-GLD-FREE',3,449,0,67.35),
('SHOP-1129','WDRS-FLR-L',1,1499,0,74.95),
('SHOP-1129','WPAL-YLW-L',2,599,179.7,50.91),
('AMAZ-1104','WJNS-IND-28',1,1349,67.45,64.08),
('AMAZ-1104','WPAL-YLW-M',1,599,29.95,28.45),
('AMAZ-1104','WLHG-RED-L',3,5499,824.85,2820.99),
('AMAZ-1104','WTOP-PCH-L',1,599,29.95,28.45),
('AMAZ-1121','MSHC-RED-M',2,899,89.9,85.41),
('AMAZ-1121','MHOD-BLK-XL',1,1299,129.9,58.45),
('FLIP-1102','MCHN-KHK-34',1,1199,0,59.95),
('FLIP-1102','MSHC-RED-L',1,899,89.9,40.45),
('FLIP-1102','BTEE-BLU-89Y',1,329,0,16.45),
('AMAZ-1107','WPAL-WHT-L',1,599,59.9,26.95),
('AMAZ-1112','WJKT-BLK-XL',1,2699,0,485.82),
('AMAZ-1112','WLHG-RED-M',1,5499,824.85,841.35),
('SHOP-1105','MSHC-RED-XL',1,899,134.85,38.21),
('SHOP-1105','MHOD-BLK-M',1,1299,0,64.95),
('SHOP-1105','MJNS-IND-34',1,1399,0,69.95),
('SHOP-1105','BTRK-BLK-67Y',2,999,199.8,89.91),
('FLIP-1101','GLEG-BLK-89Y',1,279,0,13.95),
('FLIP-1101','GFRK-PNK-89Y',1,749,0,37.45),
('FLIP-1101','GJNS-IND-1011Y',1,779,116.85,33.11),
('FLIP-1101','GLHG-TEL-67Y',1,1999,0,99.95),
('SHOP-1109','WKRT-PNK-M',1,849,42.45,40.33),
('SHOP-1109','WJNS-BLK-28',1,1349,0,67.45),
('SHOP-1117','MBLZ-NVY-38',2,3799,0,1367.64),
('SHOP-1117','MHOD-GRY-L',1,1299,0,64.95),
('SHOP-1117','MJNS-BLK-32',1,1399,69.95,66.45),
('SHOP-1117','MTEE-WHT-M',1,449,0,22.45),
('SHOP-1128','MJNS-BLK-32',1,1399,69.95,66.45),
('SHOP-1128','MBLZ-NVY-38',2,3799,759.8,1230.88),
('SHOP-1128','MCHN-KHK-34',2,1199,119.9,113.91),
('SHOP-1128','MSHC-RED-M',3,899,0,134.85),
('FLIP-1103','GTOP-YLW-45Y',1,349,0,17.45),
('FLIP-1103','WLHG-MAG-M',1,5499,274.95,940.33),
('SHOP-1123','MTRK-BLK-M',1,649,0,32.45),
('SHOP-1124','WTOP-WHT-M',1,599,0,29.95),
('SHOP-1124','WLHG-MAG-M',1,5499,274.95,940.33),
('SHOP-1125','WTOP-WHT-L',2,599,0,59.9),
('SHOP-1126','MHOD-GRY-XL',1,1299,0,64.95),
('SHOP-1126','MSHC-RED-XL',2,899,89.9,85.41),
('SHOP-1126','MPOL-NVY-M',3,699,0,104.85),
('SHOP-1111','MJNS-BLK-32',2,1399,0,139.9),
('AMAZ-1103','MSHC-GRN-L',1,899,44.95,42.7),
('SHOP-1102','WTOP-PCH-M',1,599,0,29.95),
('SHOP-1102','WDRS-FLP-S',1,1499,74.95,71.2),
('SHOP-1102','WLEG-BLK-L',1,349,52.35,14.83)
) as v(ext,sku,q,up,d,t) join orders o on o.external_order_id=v.ext join products p on p.sku=v.sku;

-- opening stock (31 Aug 2026) = intended closing stock + units dispatched, so balances and the movement ledger agree.
-- Profile: 9 low-stock SKUs, 5 out-of-stock SKUs, discontinued SKUs with dead stock, Mumbai 3PL stocks ~65% of active SKUs.
with oos as (select unnest(array['BTEE-RED-67Y','GJNS-IND-67Y','GLEG-BLK-45Y','GLHG-TEL-89Y','MTEE-BLK-M']) sku), low as (select unnest(array['BJNS-IND-67Y','BKUR-MUS-89Y','BSHT-NVY-89Y','GLEG-PNK-67Y','GNGT-PNK-89Y','MSHF-SKY-M','WDRS-FLP-S','WJKT-BLK-L','WPAL-YLW-XL']) sku),
wh(id) as (values ('cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e'::uuid),('721474ad-510d-43e5-b0f1-b41149b4275a'::uuid)),
dem as (
  select ol.product_id, case when o.ship_to_state in ('Maharashtra','Karnataka','Tamil Nadu') then '721474ad-510d-43e5-b0f1-b41149b4275a'::uuid else 'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e'::uuid end wh, sum(ol.quantity) q
  from order_lines ol join orders o using(order_id) where o.fulfilment_status in ('shipped','delivered') group by 1,2
), fin as (
  select p.product_id, wh.id wh,
    case when p.sku in (select sku from oos) then 0
         when p.sku in (select sku from low) then (case when wh.id='cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e' then 1 + abs(hashtext(p.sku))%4 else 0 end)
         when p.status='discontinued' then (case when wh.id='cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e' then 25 + abs(hashtext(p.sku))%36 else 0 end)
         when p.status='inactive' then (case when wh.id='cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e' then 5 + abs(hashtext(p.sku))%16 else 0 end)
         when wh.id='cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e' then 25 + abs(hashtext(p.sku))%86
         when abs(hashtext(p.sku||'m'))%100 < 65 then 8 + abs(hashtext(p.sku||'q'))%38 else 0 end f
  from products p cross join wh where p.sku ~ '^[A-Z]+-[A-Z]+-' and p.sku not in ('BAG-CNV','BOTL-750','EARBUD-PRO','MUG-350','SLEEVE-14','TS-BLK-M','TS-WHT-M','YOGA-6MM')
)
select record_inventory_movement(fin.product_id, fin.wh, 'initial_stock', fin.f + coalesce(dem.q,0), 'opening', null)
from fin left join dem on dem.product_id=fin.product_id and dem.wh=fin.wh where fin.f + coalesce(dem.q,0) > 0;
update inventory_transactions set created_at='2026-08-31 09:00+05:30' where movement_type='initial_stock' and created_at > '2026-10-01';

-- dispatch (stock out) for shipped / delivered / RTO-bound orders, from the Mumbai 3PL for MH/KA/TN, else Surat
select record_inventory_movement(ol.product_id, case when o.ship_to_state in ('Maharashtra','Karnataka','Tamil Nadu') then '721474ad-510d-43e5-b0f1-b41149b4275a'::uuid else 'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e'::uuid end, 'sale_dispatch', -ol.quantity, 'order', o.order_id)
from order_lines ol join orders o using(order_id) where o.fulfilment_status in ('shipped','delivered') and o.external_order_id ~ '^(SHOP|AMAZ|FLIP)-11'
order by o.order_date;
update inventory_transactions it set created_at = o.order_date + interval '14 hours' from orders o
  where it.movement_type='sale_dispatch' and it.reference_id=o.order_id and it.created_at > '2026-10-01';

-- invoices + sales vouchers via the real posting engine (shipped, delivered and RTO-bound orders); RTO status flips afterwards
select post_sales_voucher(order_id) from orders where fulfilment_status in ('shipped','delivered') and external_order_id ~ '^(SHOP|AMAZ|FLIP)-11' order by order_date;
update orders set fulfilment_status='rto' where external_order_id in ('SHOP-1132','SHOP-1122','AMAZ-1114','FLIP-1106','SHOP-1101','AMAZ-1118');

-- order timeline: earlier stages (the trigger logged the insert-time status and the RTO flip)
insert into order_status_history (order_id, fulfilment_status, payment_status, changed_by)
select o.order_id, s.fs, case when s.fs='pending' or o.payment_type='cod' then 'pending' else 'paid' end, null
from orders o cross join lateral unnest(
  case o.fulfilment_status when 'processing' then array['pending'] when 'shipped' then array['pending','processing']
       when 'delivered' then array['pending','processing','shipped'] when 'cancelled' then array['pending']
       when 'rto' then array['pending','processing'] else array[]::text[] end) s(fs)
where o.external_order_id ~ '^(SHOP|AMAZ|FLIP)-11' and o.fulfilment_status in ('processing','shipped','delivered','cancelled','rto');
update order_status_history h set changed_at = o.order_date + (case h.fulfilment_status when 'pending' then interval '0' when 'processing' then interval '6 hours'
   when 'shipped' then interval '30 hours' when 'delivered' then interval '4 days' when 'cancelled' then interval '5 hours' else interval '8 days' end)
from orders o where o.order_id=h.order_id and o.external_order_id ~ '^(SHOP|AMAZ|FLIP)-11';

-- COD collections (delivered = cash collected by courier; shipped/RTO = still pending)
insert into cod_collections (order_id, courier_name, cod_amount, collected_amount, remitted_amount, status, collected_date)
select o.order_id, v.cr, o.net_amount, case when v.st='collected' then o.net_amount else 0 end, 0, v.st, v.cd::date from (values
('AMAZ-1106','Delhivery - Sachin GIDC Surat','collected','2026-09-08'),
('SHOP-1112','Bluedart - Surat City','collected','2026-09-10'),
('SHOP-1119','Ecom Express - Udhna Hub','collected','2026-09-09'),
('SHOP-1114','Bluedart - Surat City','collected','2026-09-08'),
('SHOP-1113','Ecom Express - Udhna Hub','collected','2026-09-11'),
('SHOP-1122','Xpressbees - Pandesara','pending',null),
('FLIP-1115','Bluedart - Surat City','collected','2026-09-13'),
('SHOP-1116','Xpressbees - Pandesara','collected','2026-09-12'),
('SHOP-1121','DTDC - Ring Road Surat','collected','2026-09-13'),
('FLIP-1112','Xpressbees - Pandesara','collected','2026-09-18'),
('SHOP-1131','Ecom Express - Udhna Hub','collected','2026-09-16'),
('AMAZ-1115','Ecom Express - Udhna Hub','collected','2026-09-21'),
('FLIP-1111','Xpressbees - Pandesara','collected','2026-09-21'),
('FLIP-1113','Bluedart - Surat City','collected','2026-09-21'),
('AMAZ-1111','Ecom Express - Udhna Hub','collected','2026-09-21'),
('SHOP-1107','Xpressbees - Pandesara','collected','2026-09-27'),
('SHOP-1104','Bluedart - Surat City','collected','2026-09-30'),
('FLIP-1107','Delhivery - Sachin GIDC Surat','collected','2026-09-28')
) as v(ext,cr,st,cd) join orders o on o.external_order_id=v.ext;

select record_cod_remittance(c.cod_id, c.cod_amount) from cod_collections c join orders o using(order_id) where o.external_order_id in ('SHOP-1116','SHOP-1107','FLIP-1115','SHOP-1113','FLIP-1111','SHOP-1114','SHOP-1121','SHOP-1119','FLIP-1113','SHOP-1104');
select record_cod_remittance(c.cod_id, round(c.cod_amount*0.6,2)) from cod_collections c join orders o using(order_id) where o.external_order_id='AMAZ-1115';
select record_cod_remittance(c.cod_id, round(c.cod_amount*0.6,2)) from cod_collections c join orders o using(order_id) where o.external_order_id='SHOP-1131';

-- returns (mostly arriving via webhook; a few manual fallbacks)
insert into returns (order_id, return_reason, status, pickup_date, received_date, restock_status, refund_status, warehouse_id, source)
select o.order_id, v.rs, v.st, v.pd::date, v.rd::date, 'pending', 'pending', v.wh::uuid, v.src from (values
('SHOP-1130','Wrong item delivered','requested',null,null,'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('AMAZ-1116','Colour different from photo','requested',null,null,'721474ad-510d-43e5-b0f1-b41149b4275a','webhook'),
('FLIP-1110','Customer changed mind','approved',null,null,'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('FLIP-1117','Colour different from photo','pickup','2026-09-15',null,'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('SHOP-1112','Wrong item delivered','in_transit','2026-09-13',null,'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('FLIP-1118','Wrong item delivered','received','2026-09-14','2026-09-16','cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','manual'),
('AMAZ-1115','Wrong item delivered','received','2026-09-24','2026-09-26','721474ad-510d-43e5-b0f1-b41149b4275a','webhook'),
('AMAZ-1119','Colour different from photo','received','2026-09-25','2026-09-27','cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('SHOP-1119','Item arrived damaged','received','2026-09-17','2026-09-19','cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('FLIP-1114','Item arrived damaged','received','2026-09-19','2026-09-21','cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('SHOP-1106','Fabric quality not as expected','received','2026-09-29','2026-10-01','cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('SHOP-1115','Colour different from photo','rejected',null,null,'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','manual')
) as v(ext,rs,st,pd,rd,wh,src) join orders o on o.external_order_id=v.ext;

select disposition_return(r.return_id, 'good', 'restocked') from returns r join orders o using(order_id) where o.external_order_id='AMAZ-1119';
select disposition_return(r.return_id, 'good', 'restocked') from returns r join orders o using(order_id) where o.external_order_id='SHOP-1119';
select disposition_return(r.return_id, 'damaged', 'quarantined') from returns r join orders o using(order_id) where o.external_order_id='FLIP-1114';
select disposition_return(r.return_id, 'wrong_item', 'claimed') from returns r join orders o using(order_id) where o.external_order_id='SHOP-1106';
update returns r set refund_status='refunded' from orders o where o.order_id=r.order_id and r.status in ('restocked','quarantined','claimed') and o.external_order_id in ('AMAZ-1119','SHOP-1119','FLIP-1114','SHOP-1106');
update returns r set refund_status='rejected' from orders o where o.order_id=r.order_id and o.external_order_id='SHOP-1115';
update returns set refund_status='processing' where status='received' and refund_status='pending';

-- credit notes with proper CGST/SGST/IGST reversal for refunded returns
do $$
declare r record; v_vt uuid; v_per uuid; v_vid uuid; v_recv uuid; v_sales uuid; v_cg uuid; v_sg uuid; v_ig uuid; v_cs text; v_half numeric; v_n int;
begin
  select voucher_type_id into v_vt from voucher_types where code='CREDIT_NOTE';
  select ledger_id into v_recv from ledgers where name='Trade Receivables';
  select ledger_id into v_sales from ledgers where name='Sales Revenue';
  select ledger_id into v_cg from ledgers where name='CGST Payable (Output)';
  select ledger_id into v_sg from ledgers where name='SGST Payable (Output)';
  select ledger_id into v_ig from ledgers where name='IGST Payable (Output)';
  select state into v_cs from companies limit 1;
  select count(*) into v_n from credit_notes;
  for r in select ret.return_id, i.invoice_id, i.taxable_value, i.gst_amount, i.total, o.ship_to_state, ret.received_date
           from returns ret join orders o using(order_id) join invoices i on i.order_id=o.order_id
           where ret.refund_status='refunded' and not exists (select 1 from credit_notes cn where cn.return_id=ret.return_id)
           order by ret.received_date loop
    select accounting_period_id into v_per from accounting_periods where r.received_date between start_date and end_date and status='open' limit 1;
    continue when v_per is null;
    v_n := v_n + 1;
    insert into vouchers (voucher_type_id, voucher_no, voucher_date, accounting_period_id, status, source_type, source_id, narration, total_debit, total_credit)
    values (v_vt, 'CN-2026-' || lpad(v_n::text,5,'0'), r.received_date, v_per, 'draft', 'return', r.return_id,
            'Credit note for returned goods - ' || case when r.ship_to_state is distinct from v_cs then 'IGST' else 'CGST+SGST' end, r.total, r.total)
    returning voucher_id into v_vid;
    insert into voucher_lines (voucher_id, ledger_id, debit, credit, reference_type, reference_id) values (v_vid, v_sales, r.taxable_value, 0, 'return', r.return_id);
    if r.gst_amount > 0 then
      if r.ship_to_state is distinct from v_cs then
        insert into voucher_lines (voucher_id, ledger_id, debit, credit, reference_type, reference_id) values (v_vid, v_ig, r.gst_amount, 0, 'return', r.return_id);
      else
        v_half := round(r.gst_amount/2, 2);
        if v_half > 0 then insert into voucher_lines (voucher_id, ledger_id, debit, credit, reference_type, reference_id) values (v_vid, v_cg, v_half, 0, 'return', r.return_id); end if;
        if r.gst_amount - v_half > 0 then insert into voucher_lines (voucher_id, ledger_id, debit, credit, reference_type, reference_id) values (v_vid, v_sg, r.gst_amount - v_half, 0, 'return', r.return_id); end if;
      end if;
    end if;
    insert into voucher_lines (voucher_id, ledger_id, debit, credit, reference_type, reference_id) values (v_vid, v_recv, 0, r.total, 'return', r.return_id);
    update vouchers set status='posted' where voucher_id=v_vid;
    insert into credit_notes (invoice_id, return_id, amount, tax_amount, date, status, voucher_id)
    values (r.invoice_id, r.return_id, r.total, r.gst_amount, r.received_date, 'posted', v_vid);
  end loop;
end $$;

-- RTOs (courier-initiated; mostly via webhook)
insert into rtos (order_id, awb, reason, status, received_date, warehouse_id, source)
select o.order_id, v.awb, v.rs, v.st, v.rd::date, v.wh::uuid, v.src from (values
('SHOP-1132','AWB6236222495','Customer unreachable','initiated',null,'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('SHOP-1122','AWB9530335091','Customer unreachable','in_transit',null,'cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('AMAZ-1114','AWB2833448443','Delivery attempts exhausted','received','2026-09-21','cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','webhook'),
('FLIP-1106','AWB4834839948','Delivery attempts exhausted','received','2026-09-23','cbbf5d13-e7e0-450d-bb37-6e5f09e82f4e','manual'),
('SHOP-1101','AWB8473657737','Delivery attempts exhausted','received','2026-10-02','721474ad-510d-43e5-b0f1-b41149b4275a','webhook'),
('AMAZ-1118','AWB9005864948','Address incomplete','received','2026-10-02','721474ad-510d-43e5-b0f1-b41149b4275a','webhook')
) as v(ext,awb,rs,st,rd,wh,src) join orders o on o.external_order_id=v.ext;

select disposition_rto(r.rto_id, 'good', 'restocked') from rtos r join orders o using(order_id) where o.external_order_id='FLIP-1106';
select disposition_rto(r.rto_id, 'damaged', 'quarantined') from rtos r join orders o using(order_id) where o.external_order_id='SHOP-1101';

-- settlements per channel per fortnight, derived from delivered prepaid orders. Fee lines carry GST (feeds ITC on reconcile).
-- Amazon 14% + Rs38 shipping, Flipkart 13% + Rs42 shipping, Shopify 2% gateway fee (all GST-inclusive deductions).
do $$
declare w record; s uuid; o record; comm numeric; shp numeric; v_ded numeric; v_gross numeric; pct numeric; ship numeric; pref text;
begin
  for w in select c.channel_id, c.name, x.ws, x.we, x.tag from channels c
           cross join (values ('2026-09-01'::date,'2026-09-15'::date,'S1'),('2026-09-16','2026-09-30','S2')) x(ws,we,tag) loop
    pct := case when w.name like 'Amazon%' then .14 when w.name like 'Flipkart%' then .13 else .02 end;
    ship := case when w.name like 'Amazon%' then 38 when w.name like 'Flipkart%' then 42 else 0 end;
    pref := case when w.name like 'Amazon%' then 'AMZ' when w.name like 'Flipkart%' then 'FK' else 'SHP' end;
    v_gross := 0; v_ded := 0; s := null;
    for o in select * from orders where channel_id=w.channel_id and fulfilment_status='delivered' and order_date::date between w.ws and w.we
                and payment_type='prepaid' and external_order_id ~ '^(SHOP|AMAZ|FLIP)-11' order by order_date loop
      if s is null then
        insert into settlements (channel_id, external_settlement_id, period_start, period_end, gross, deductions, expected_amount, status)
        values (w.channel_id, pref||'-SETTLE-2026-09-'||w.tag, w.ws, w.we, 0, 0, 0, 'pending') returning settlement_id into s;
      end if;
      comm := round(o.net_amount*pct/1.18, 2); shp := round(ship/1.18, 2);
      insert into settlement_lines (settlement_id, order_id, fee_type, amount, tax_amount) values (s, o.order_id, 'order_value', o.net_amount, 0);
      insert into settlement_lines (settlement_id, order_id, fee_type, amount, tax_amount)
        values (s, o.order_id, case when pref='SHP' then 'gateway_fee' else 'commission' end, comm, round(comm*.18,2));
      if shp > 0 then insert into settlement_lines (settlement_id, order_id, fee_type, amount, tax_amount) values (s, o.order_id, 'shipping', shp, round(shp*.18,2)); end if;
      v_gross := v_gross + o.net_amount; v_ded := v_ded + comm + round(comm*.18,2) + shp + round(shp*.18,2);
    end loop;
    if s is not null then
      update settlements set gross=v_gross, deductions=round(v_ded,2), expected_amount=round(v_gross - v_ded,2) where settlement_id=s;
    end if;
  end loop;
end $$;

-- bank credits + reconciliation through the engine: Sep-A settlements - Amazon exact, Flipkart short-paid, Shopify exact, Sep S2 left pending
insert into bank_transactions (bank_account_id, txn_date, reference, amount, type, match_status)
select 'd49edd6e-b260-4a23-b8d5-deac2ee71c20', '2026-09-20'::date + (row_number() over (order by external_settlement_id))::int,
  'NEFT-'||external_settlement_id, case when external_settlement_id like 'FK-%' then expected_amount - 140 else expected_amount end, 'credit', 'unmatched'
from settlements where external_settlement_id in ('AMZ-SETTLE-2026-09-S1','FK-SETTLE-2026-09-S1','SHP-SETTLE-2026-09-S1');
select reconcile_settlement(s.settlement_id, b.amount, b.bank_txn_id)
from settlements s join bank_transactions b on b.reference='NEFT-'||s.external_settlement_id
where s.external_settlement_id in ('AMZ-SETTLE-2026-09-S1','FK-SETTLE-2026-09-S1','SHP-SETTLE-2026-09-S1');
insert into bank_transactions (bank_account_id, txn_date, reference, amount, type, match_status) values
 ('ddd25939-a85f-40ed-9751-77c4de11082c','2026-09-12','UPI-CR-8801223344',1499,'credit','unmatched'),
 ('ddd25939-a85f-40ed-9751-77c4de11082c','2026-09-19','UPI-CR-8801556677',2398,'credit','unmatched'),
 ('d49edd6e-b260-4a23-b8d5-deac2ee71c20','2026-09-25','COURIER-FREIGHT-SEP26',4260,'debit','unmatched'),
 ('d49edd6e-b260-4a23-b8d5-deac2ee71c20','2026-09-28','PACKAGING-MATERIAL-SURAT',7850,'debit','unmatched'),
 ('d49edd6e-b260-4a23-b8d5-deac2ee71c20','2026-09-30','BANK-CHARGES-SEP26',236,'debit','unmatched');

-- claims across every lifecycle state, advanced through the real state machine
insert into claims (order_id, claim_type, potential_amount, deadline, owner, status)
select o.order_id, v.ct, case when v.ct in ('incorrect_deduction','excess_deduction') then round(o.net_amount*.08,2) else o.net_amount end, v.dl::date, 'f08a6962-1e79-4a95-85a8-e59910ebdaff', 'potential' from (values
('SHOP-1132','lost_shipment','2026-10-03'),
('AMAZ-1118','lost_shipment','2026-10-10'),
('FLIP-1114','damaged_return','2026-10-29'),
('SHOP-1106','other','2026-10-06'),
('AMAZ-1110','incorrect_deduction','2026-10-19'),
('FLIP-1118','excess_deduction','2026-10-26')
) as v(ext,ct,dl) join orders o on o.external_order_id=v.ext;
select advance_claim(c.claim_id,'claimed') from claims c join orders o using(order_id) where o.external_order_id='AMAZ-1118' and c.claim_type='lost_shipment';
select advance_claim(c.claim_id,'claimed') from claims c join orders o using(order_id) where o.external_order_id='FLIP-1114' and c.claim_type='damaged_return';
select advance_claim(c.claim_id,'approved') from claims c join orders o using(order_id) where o.external_order_id='FLIP-1114' and c.claim_type='damaged_return';
select advance_claim(c.claim_id,'claimed') from claims c join orders o using(order_id) where o.external_order_id='SHOP-1106' and c.claim_type='other';
select advance_claim(c.claim_id,'rejected') from claims c join orders o using(order_id) where o.external_order_id='SHOP-1106' and c.claim_type='other';
select advance_claim(c.claim_id,'claimed') from claims c join orders o using(order_id) where o.external_order_id='AMAZ-1110' and c.claim_type='incorrect_deduction';
select advance_claim(c.claim_id,'approved') from claims c join orders o using(order_id) where o.external_order_id='AMAZ-1110' and c.claim_type='incorrect_deduction';
select advance_claim(c.claim_id,'recovered', c.approved_amount) from claims c join orders o using(order_id) where o.external_order_id='AMAZ-1110' and c.claim_type='incorrect_deduction';
select advance_claim(c.claim_id,'claimed') from claims c join orders o using(order_id) where o.external_order_id='FLIP-1118' and c.claim_type='excess_deduction';
select advance_claim(c.claim_id,'approved') from claims c join orders o using(order_id) where o.external_order_id='FLIP-1118' and c.claim_type='excess_deduction';