-- 0054: Bank reconciliation (bank book vs bank statement).
--
--   * bank statement lines come from a feed (API pull, API push, CSV upload, or typed in) -> bank_transactions
--   * the "bank book" is every posted voucher line on that bank account's ledger (created in 0049)
--   * ADMIN-EDITABLE MATCH RULES (bank_recon_rules) decide how a statement line is paired with book entries:
--       auto_reconcile = link them, suggest = put a proposal in front of a human, exclude = keep the line out of the books
--   * a human can always override: match by hand, undo a match, exclude a line, include it again, book a missing entry
--   * a statement line that is already recorded in the books is MATCHED (never booked twice); a duplicate import is EXCLUDED
--   * order on import: 1) match against existing book entries  2) otherwise the Rule Book (0050) books it  3) otherwise Suspense draft
--
-- Nothing here edits a posted voucher. Reversals are new vouchers.

-- ---------------------------------------------------------------- statement line extras
alter table bank_transactions
  add column if not exists external_txn_id text,
  add column if not exists value_date      date,
  add column if not exists balance         numeric(14,2),
  add column if not exists source          text not null default 'manual',
  add column if not exists line_hash       text,
  add column if not exists recon_status    text not null default 'unreconciled',
  add column if not exists recon_note      text,
  add column if not exists excluded_reason text,
  add column if not exists excluded_by     uuid,
  add column if not exists excluded_at     timestamptz,
  add column if not exists raw             jsonb,
  add column if not exists import_seq      bigint generated by default as identity;

alter table bank_transactions drop constraint if exists bank_transactions_source_check;
alter table bank_transactions add constraint bank_transactions_source_check check (source in ('manual','csv','api','system'));
alter table bank_transactions drop constraint if exists bank_transactions_recon_status_check;
alter table bank_transactions add constraint bank_transactions_recon_status_check
  check (recon_status in ('unreconciled','suggested','reconciled','excluded'));
alter table bank_transactions drop constraint if exists bank_transactions_excluded_reason_check;
alter table bank_transactions add constraint bank_transactions_excluded_reason_check
  check (excluded_reason is null or excluded_reason in ('duplicate_import','own_transfer','not_business','other'));

alter table bank_transactions drop constraint if exists bank_transactions_matched_entity_check;
alter table bank_transactions add constraint bank_transactions_matched_entity_check
  check (matched_entity is null or matched_entity = any (array['settlement','cod','order','journal_rule','book_entry','excluded']));

create unique index if not exists bank_txn_external_uq on bank_transactions (bank_account_id, external_txn_id) where external_txn_id is not null;
create unique index if not exists bank_txn_hash_uq     on bank_transactions (bank_account_id, line_hash)       where line_hash is not null;
create index if not exists bank_txn_recon_idx          on bank_transactions (bank_account_id, recon_status, txn_date);

-- ---------------------------------------------------------------- feed settings (one row per bank account)
create table if not exists bank_feeds (
  bank_account_id          uuid primary key references bank_accounts(bank_account_id) on delete cascade,
  provider                 text not null default 'manual' check (provider in ('manual','csv','api_pull','api_push')),
  enabled                  boolean not null default false,
  endpoint_url             text,
  http_method              text not null default 'GET' check (http_method in ('GET','POST')),
  auth_header_name         text not null default 'Authorization',
  secret_name              text,            -- NAME of the Edge Function secret that holds the bank API token (the token itself is never stored here)
  field_map                jsonb not null default '{}'::jsonb,
  sync_from                date,
  statement_opening_balance numeric(14,2) not null default 0,   -- bank statement balance before the first imported line
  last_synced_at           timestamptz,
  last_status              text,
  last_message             text,
  updated_by               uuid,
  updated_at               timestamptz not null default now()
);

-- ---------------------------------------------------------------- match rules (admin-editable)
create table if not exists bank_recon_rules (
  recon_rule_id        uuid primary key default gen_random_uuid(),
  rule_code            text not null unique,
  name                 text not null,
  description          text,
  priority             int  not null default 100,
  status               text not null default 'active' check (status in ('active','inactive')),
  is_system            boolean not null default false,
  version              int  not null default 1,
  default_definition   jsonb,
  bank_account_id      uuid references bank_accounts(bank_account_id) on delete cascade,   -- null = every bank account
  direction            text not null default 'any' check (direction in ('any','credit','debit')),
  action               text not null check (action in ('auto_reconcile','suggest','exclude')),
  match_type           text not null default 'one_to_one' check (match_type in ('one_to_one','sum_of_entries')),
  amount_tolerance     numeric(14,2) not null default 0 check (amount_tolerance >= 0),
  amount_tolerance_pct numeric(6,3)  not null default 0 check (amount_tolerance_pct >= 0),
  date_window_days     int  not null default 3 check (date_window_days between 0 and 90),
  reference_mode       text not null default 'ignore' check (reference_mode in ('ignore','required')),
  keyword_operator     text check (keyword_operator is null or keyword_operator in ('contains','contains_any','starts_with','ends_with','regex','equals')),
  keyword_value        text,
  book_source_types    text[],
  book_voucher_types   text[],
  exclude_reason       text check (exclude_reason is null or exclude_reason in ('own_transfer','not_business','other')),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  updated_by           uuid
);

create table if not exists bank_recon_matches (
  match_id         uuid primary key default gen_random_uuid(),
  bank_txn_id      uuid not null references bank_transactions(bank_txn_id) on delete cascade,
  voucher_line_id  uuid not null references voucher_lines(voucher_line_id),
  amount           numeric(14,2) not null,
  method           text not null check (method in ('auto_rule','manual','rule_booked','suggestion')),
  recon_rule_code  text,
  note             text,
  matched_by       uuid,
  matched_at       timestamptz not null default now(),
  status           text not null default 'active' check (status in ('active','undone')),
  undone_by        uuid,
  undone_at        timestamptz
);
create unique index if not exists bank_recon_match_line_uq on bank_recon_matches (voucher_line_id) where status = 'active';
create index if not exists bank_recon_match_txn_idx on bank_recon_matches (bank_txn_id) where status = 'active';

create table if not exists bank_recon_suggestions (
  suggestion_id    uuid primary key default gen_random_uuid(),
  bank_txn_id      uuid not null references bank_transactions(bank_txn_id) on delete cascade,
  voucher_line_ids uuid[] not null,
  recon_rule_code  text,
  score            int not null default 0,
  status           text not null default 'pending' check (status in ('pending','accepted','rejected','withdrawn')),
  created_at       timestamptz not null default now(),
  decided_by       uuid,
  decided_at       timestamptz
);
create index if not exists bank_recon_sugg_txn_idx on bank_recon_suggestions (bank_txn_id, status);

create table if not exists bank_recon_book_exclusions (
  voucher_line_id uuid primary key references voucher_lines(voucher_line_id),
  reason          text not null,
  excluded_by     uuid,
  excluded_at     timestamptz not null default now()
);

-- ---------------------------------------------------------------- RLS
alter table bank_feeds                 enable row level security;
alter table bank_recon_rules           enable row level security;
alter table bank_recon_matches         enable row level security;
alter table bank_recon_suggestions     enable row level security;
alter table bank_recon_book_exclusions enable row level security;
drop policy if exists "recon view" on bank_feeds;                 create policy "recon view" on bank_feeds                 for select to authenticated using (has_bankcod_view());
drop policy if exists "recon view" on bank_recon_rules;           create policy "recon view" on bank_recon_rules           for select to authenticated using (has_bankcod_view());
drop policy if exists "recon view" on bank_recon_matches;         create policy "recon view" on bank_recon_matches         for select to authenticated using (has_bankcod_view());
drop policy if exists "recon view" on bank_recon_suggestions;     create policy "recon view" on bank_recon_suggestions     for select to authenticated using (has_bankcod_view());
drop policy if exists "recon view" on bank_recon_book_exclusions; create policy "recon view" on bank_recon_book_exclusions for select to authenticated using (has_bankcod_view());
revoke all on bank_feeds, bank_recon_rules, bank_recon_matches, bank_recon_suggestions, bank_recon_book_exclusions from anon;
revoke insert, update, delete on bank_feeds, bank_recon_rules, bank_recon_matches, bank_recon_suggestions, bank_recon_book_exclusions from authenticated;

-- ---------------------------------------------------------------- helpers
create or replace function br_norm(p text) returns text
language sql immutable set search_path = public, pg_temp as $$
  select upper(regexp_replace(coalesce(p, ''), '[^A-Za-z0-9]', '', 'g'))
$$;

-- reference-like words that tie a book entry to a bank narration (voucher no, settlement id, order no, AWB-like words)
create or replace function br_tokens(p_voucher_no text, p_narr text, p_source_type text, p_source_id uuid) returns text[]
language plpgsql stable security definer set search_path = public, pg_temp as $$
declare v text[] := '{}';
begin
  v := array[br_norm(p_voucher_no)];
  v := v || coalesce((select array_agg(distinct br_norm(w)) from regexp_split_to_table(coalesce(p_narr, ''), '[^A-Za-z0-9\-/]+') w
                       where length(br_norm(w)) >= 5 and w ~ '[0-9]'), '{}');
  if p_source_type = 'settlement' then
    v := v || coalesce((select array[br_norm(external_settlement_id)] from settlements where settlement_id = p_source_id), '{}');
  elsif p_source_type = 'cod' then
    v := v || coalesce((select array[br_norm(o.external_order_id)] from cod_collections c join orders o on o.order_id = c.order_id where c.cod_id = p_source_id), '{}');
  end if;
  return array(select distinct k from unnest(v) k where length(k) >= 5);
end $$;

create or replace function br_bank_ledger_of(p_bank_account_id uuid) returns uuid
language sql stable security definer set search_path = public, pg_temp as $$
  select ledger_id from bank_accounts where bank_account_id = p_bank_account_id
$$;

-- Book entries that could pair with a statement line: posted lines on the bank ledger, right side, not already spoken for.
create or replace function br_candidates(p_txn_id uuid, p_window int, p_sources text[] default null, p_vtypes text[] default null)
returns table (voucher_line_id uuid, voucher_id uuid, voucher_no text, voucher_date date, amount numeric, narration text,
               source_type text, tokens text[], day_gap int)
language plpgsql stable security definer set search_path = public, pg_temp as $$
declare t bank_transactions%rowtype; v_ledger uuid;
begin
  select * into t from bank_transactions where bank_txn_id = p_txn_id;
  if not found then return; end if;
  v_ledger := br_bank_ledger_of(t.bank_account_id);
  if v_ledger is null then return; end if;
  return query
  select vl.voucher_line_id, v.voucher_id, v.voucher_no, v.voucher_date,
         (case when t.type = 'credit' then vl.debit else vl.credit end)::numeric,
         coalesce(vl.narration, v.narration), v.source_type,
         br_tokens(v.voucher_no, coalesce(vl.narration, v.narration), v.source_type, v.source_id),
         abs(v.voucher_date - t.txn_date)::int
    from voucher_lines vl
    join vouchers v on v.voucher_id = vl.voucher_id
    join voucher_types vt on vt.voucher_type_id = v.voucher_type_id
   where vl.ledger_id = v_ledger and v.status = 'posted'
     and ((t.type = 'credit' and vl.debit > 0) or (t.type = 'debit' and vl.credit > 0))
     and abs(v.voucher_date - t.txn_date) <= p_window
     and (p_sources is null or v.source_type = any (p_sources))
     and (p_vtypes  is null or vt.code = any (p_vtypes))
     and not exists (select 1 from bank_recon_matches m where m.voucher_line_id = vl.voucher_line_id and m.status = 'active')
     and not exists (select 1 from bank_recon_book_exclusions x where x.voucher_line_id = vl.voucher_line_id)
     and coalesce(v.source_type, '') <> 'reversal'
     and not exists (select 1 from vouchers rv where rv.source_type = 'reversal' and rv.source_id = v.voucher_id and rv.status = 'posted');
end $$;

-- Pair a statement line with book entries.
create or replace function br_link(p_txn uuid, p_line_ids uuid[], p_method text, p_rule_code text, p_note text) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
declare t bank_transactions%rowtype; l uuid; v_amt numeric; v_vid uuid;
begin
  if p_method <> 'rule_booked' then perform br_cancel_rule_draft(p_txn); end if;
  select * into t from bank_transactions where bank_txn_id = p_txn;
  foreach l in array p_line_ids loop
    select (case when t.type = 'credit' then vl.debit else vl.credit end), vl.voucher_id into v_amt, v_vid
      from voucher_lines vl where vl.voucher_line_id = l;
    insert into bank_recon_matches (bank_txn_id, voucher_line_id, amount, method, recon_rule_code, note, matched_by)
    values (p_txn, l, v_amt, p_method, p_rule_code, p_note, auth.uid());
  end loop;
  select vl.voucher_id into v_vid from voucher_lines vl where vl.voucher_line_id = p_line_ids[1];
  update bank_transactions
     set recon_status = 'reconciled', recon_note = coalesce(p_note, recon_note),
         match_status = 'matched',
         matched_entity = coalesce(matched_entity, case when p_method = 'rule_booked' then 'journal_rule' else 'book_entry' end),
         matched_reference_id = coalesce(matched_reference_id, v_vid),
         excluded_reason = null, excluded_by = null, excluded_at = null
   where bank_txn_id = p_txn;
  update bank_recon_suggestions set status = case when voucher_line_ids @> p_line_ids and p_line_ids @> voucher_line_ids then 'accepted' else 'withdrawn' end,
         decided_by = auth.uid(), decided_at = now()
   where bank_txn_id = p_txn and status = 'pending';
end $$;

-- Link the bank leg of a voucher that was created FROM this statement line by the Rule Book.
create or replace function br_link_rule_voucher(p_txn uuid, p_voucher uuid) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
declare t bank_transactions%rowtype; v_ledger uuid; v_ids uuid[];
begin
  select * into t from bank_transactions where bank_txn_id = p_txn;
  if not found then return; end if;
  if not exists (select 1 from vouchers where voucher_id = p_voucher and status = 'posted') then return; end if;
  v_ledger := br_bank_ledger_of(t.bank_account_id);
  select array_agg(vl.voucher_line_id) into v_ids from voucher_lines vl
   where vl.voucher_id = p_voucher and vl.ledger_id = v_ledger
     and ((t.type = 'credit' and vl.debit > 0) or (t.type = 'debit' and vl.credit > 0))
     and not exists (select 1 from bank_recon_matches m where m.voucher_line_id = vl.voucher_line_id and m.status = 'active');
  if v_ids is null then return; end if;
  perform br_link(p_txn, v_ids, 'rule_booked', null, 'Booked from this bank line by a rule');
end $$;

-- Undo active matches (statement line goes back to unreconciled).
create or replace function br_unlink(p_txn uuid) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  update bank_recon_matches set status = 'undone', undone_by = auth.uid(), undone_at = now() where bank_txn_id = p_txn and status = 'active';
  update bank_transactions
     set recon_status = 'unreconciled',
         match_status = case when matched_entity in ('book_entry','excluded') then 'unmatched' else match_status end,
         matched_reference_id = case when matched_entity in ('book_entry','excluded') then null else matched_reference_id end,
         matched_entity = case when matched_entity in ('book_entry','excluded') then null else matched_entity end,
         excluded_reason = null, excluded_by = null, excluded_at = null
   where bank_txn_id = p_txn;
end $$;

-- A draft entry the Rule Book made from this line is thrown away when a human decides the line another way.
create or replace function br_cancel_rule_draft(p_txn uuid) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
declare t bank_transactions%rowtype;
begin
  select * into t from bank_transactions where bank_txn_id = p_txn;
  if t.matched_entity = 'journal_rule' and t.matched_reference_id is not null
     and exists (select 1 from vouchers where voucher_id = t.matched_reference_id and status = 'draft') then
    update vouchers set status = 'cancelled' where voucher_id = t.matched_reference_id;
    update journal_rule_log set status = 'discarded' where voucher_id = t.matched_reference_id and status = 'draft';
    update credit_notes set status = 'cancelled' where voucher_id = t.matched_reference_id and status = 'draft';
    update bank_transactions set matched_entity = null, matched_reference_id = null, match_status = 'unmatched' where bank_txn_id = p_txn;
  end if;
end $$;

-- A reversing journal for a posted voucher (posted vouchers are never edited).
create or replace function br_reverse_voucher(p_voucher uuid, p_reason text) returns uuid
language plpgsql security definer set search_path = public, pg_temp as $$
declare v vouchers%rowtype; v_new uuid; v_date date; v_period uuid; v_vt uuid; v_prefix text; v_no text;
begin
  select * into v from vouchers where voucher_id = p_voucher;
  if not found or v.status <> 'posted' then raise exception 'Only a posted voucher can be reversed'; end if;
  v_date := current_date;
  select accounting_period_id into v_period from accounting_periods where v_date between start_date and end_date and status = 'open' limit 1;
  if v_period is null then
    v_date := v.voucher_date;
    select accounting_period_id into v_period from accounting_periods where v_date between start_date and end_date and status = 'open' limit 1;
  end if;
  if v_period is null then raise exception 'No open accounting period to post the reversal in'; end if;
  select voucher_type_id, numbering_prefix into v_vt, v_prefix from voucher_types where code = 'JOURNAL';
  v_no := v_prefix || '-' || to_char(v_date, 'YYMM') || '-' || lpad(nextval('journal_voucher_seq')::text, 6, '0');
  insert into vouchers (voucher_type_id, voucher_no, voucher_date, accounting_period_id, status, source_type, source_id, narration, total_debit, total_credit, created_by)
  values (v_vt, v_no, v_date, v_period, 'draft', 'reversal', p_voucher, 'Reversal of ' || v.voucher_no || ' - ' || coalesce(p_reason, ''), v.total_debit, v.total_credit, auth.uid())
  returning voucher_id into v_new;
  insert into voucher_lines (voucher_id, ledger_id, debit, credit, narration)
  select v_new, ledger_id, credit, debit, 'Reversal' from voucher_lines where voucher_id = p_voucher;
  update vouchers set status = 'posted' where voucher_id = v_new;
  return v_new;
end $$;

-- ---------------------------------------------------------------- the matching engine
create or replace function br_apply_rules_to_txn(p_txn uuid) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  t bank_transactions%rowtype; r bank_recon_rules%rowtype;
  v_desc text; v_norm text; v_tol numeric; v_hits jsonb; v_n int; v_top int; v_same int; v_ids uuid[];
  c record; n int; mask int; i int; cnt int; v_sum numeric; v_sets jsonb; v_set uuid[]; v_k int;
  v_amts numeric[]; v_lids uuid[]; v_scores int[]; v_made int;
begin
  select * into t from bank_transactions where bank_txn_id = p_txn;
  if not found then return jsonb_build_object('skipped', 'line not found'); end if;
  if t.recon_status in ('reconciled', 'excluded') then return jsonb_build_object('skipped', 'already ' || t.recon_status); end if;
  v_desc := coalesce(t.reference, '');
  v_norm := br_norm(v_desc);

  -- start clean: old pending proposals are recomputed
  update bank_recon_suggestions set status = 'withdrawn' where bank_txn_id = p_txn and status = 'pending';

  for r in select * from bank_recon_rules
            where status = 'active' and (bank_account_id is null or bank_account_id = t.bank_account_id)
              and (direction = 'any' or direction = t.type)
            order by priority, rule_code loop

    if r.keyword_operator is not null and not jr_cond_ok(jsonb_build_object('d', v_desc), 'd', r.keyword_operator, r.keyword_value) then
      continue;
    end if;

    if r.action = 'exclude' then
      perform br_cancel_rule_draft(p_txn);
      update bank_transactions set recon_status = 'excluded', match_status = 'matched', matched_entity = 'excluded',
             excluded_reason = coalesce(r.exclude_reason, 'other'), excluded_at = now(),
             recon_note = 'Excluded by rule ' || r.rule_code || ' - ' || r.name
       where bank_txn_id = p_txn;
      return jsonb_build_object('excluded', r.rule_code);
    end if;

    v_tol := greatest(r.amount_tolerance, round(t.amount * r.amount_tolerance_pct / 100, 2));

    if r.match_type = 'one_to_one' then
      select jsonb_agg(jsonb_build_object('id', x.voucher_line_id, 'score', x.score) order by x.score desc, x.day_gap, x.voucher_date)
        into v_hits
        from (select c2.voucher_line_id, c2.day_gap, c2.voucher_date,
                     (case when exists (select 1 from unnest(c2.tokens) k where position(k in v_norm) > 0) then 50 else 0 end
                      + case when c2.amount = t.amount then 30 else 0 end + greatest(20 - c2.day_gap * 3, 0)) as score,
                     exists (select 1 from unnest(c2.tokens) k where position(k in v_norm) > 0) as ref_hit
                from br_candidates(p_txn, r.date_window_days, r.book_source_types, r.book_voucher_types) c2
               where abs(c2.amount - t.amount) <= v_tol) x
       where (r.reference_mode <> 'required' or x.ref_hit)
         and not exists (select 1 from bank_recon_suggestions s where s.bank_txn_id = p_txn and s.status = 'rejected'
                            and s.voucher_line_ids = array[x.voucher_line_id]);
      if v_hits is null then continue; end if;
      v_n := jsonb_array_length(v_hits);
      v_top := (v_hits -> 0 ->> 'score')::int;
      select count(*) into v_same from jsonb_array_elements(v_hits) e where (e ->> 'score')::int = v_top;
      if r.action = 'auto_reconcile' and v_same = 1 then
        perform br_link(p_txn, array[(v_hits -> 0 ->> 'id')::uuid], 'auto_rule', r.rule_code,
                        'Matched by rule ' || r.rule_code);
        return jsonb_build_object('reconciled', r.rule_code, 'lines', 1);
      end if;
      v_made := 0;
      for i in 0 .. least(v_n, 5) - 1 loop
        insert into bank_recon_suggestions (bank_txn_id, voucher_line_ids, recon_rule_code, score)
        values (p_txn, array[(v_hits -> i ->> 'id')::uuid], r.rule_code, (v_hits -> i ->> 'score')::int);
        v_made := v_made + 1;
      end loop;
      update bank_transactions set recon_status = 'suggested' where bank_txn_id = p_txn;
      return jsonb_build_object('suggested', r.rule_code, 'count', v_made);

    else
      -- several book entries together equal one statement line (e.g. two settlements credited as one bank entry)
      v_lids := '{}'; v_amts := '{}'; v_scores := '{}';
      for c in select c2.voucher_line_id, c2.amount,
                      (case when exists (select 1 from unnest(c2.tokens) k where position(k in v_norm) > 0) then 1 else 0 end) as hit
                 from br_candidates(p_txn, r.date_window_days, r.book_source_types, r.book_voucher_types) c2
                where c2.amount > 0 and c2.amount <= t.amount + v_tol
                order by hit desc, c2.day_gap, c2.voucher_date limit 12 loop
        v_lids := v_lids || c.voucher_line_id; v_amts := v_amts || c.amount;
      end loop;
      n := coalesce(array_length(v_lids, 1), 0);
      if n < 2 then continue; end if;
      v_sets := '[]'::jsonb;
      for mask in 1 .. (1 << n) - 1 loop
        cnt := 0; v_sum := 0;
        for i in 1 .. n loop
          if (mask & (1 << (i - 1))) <> 0 then cnt := cnt + 1; v_sum := v_sum + v_amts[i]; end if;
        end loop;
        if cnt between 2 and 5 and abs(v_sum - t.amount) <= v_tol then
          v_set := '{}';
          for i in 1 .. n loop
            if (mask & (1 << (i - 1))) <> 0 then v_set := v_set || v_lids[i]; end if;
          end loop;
          if not exists (select 1 from bank_recon_suggestions s where s.bank_txn_id = p_txn and s.status = 'rejected' and s.voucher_line_ids @> v_set and v_set @> s.voucher_line_ids) then
            v_sets := v_sets || jsonb_build_array(to_jsonb(v_set));
          end if;
          exit when jsonb_array_length(v_sets) >= 3;
        end if;
      end loop;
      if jsonb_array_length(v_sets) = 0 then continue; end if;
      if r.action = 'auto_reconcile' and jsonb_array_length(v_sets) = 1 then
        select array_agg(x::uuid) into v_set from jsonb_array_elements_text(v_sets -> 0) x;
        perform br_link(p_txn, v_set, 'auto_rule', r.rule_code, 'Several entries matched by rule ' || r.rule_code);
        return jsonb_build_object('reconciled', r.rule_code, 'lines', cardinality(v_set));
      end if;
      for i in 0 .. jsonb_array_length(v_sets) - 1 loop
        select array_agg(x::uuid) into v_set from jsonb_array_elements_text(v_sets -> i) x;
        insert into bank_recon_suggestions (bank_txn_id, voucher_line_ids, recon_rule_code, score) values (p_txn, v_set, r.rule_code, 40);
      end loop;
      update bank_transactions set recon_status = 'suggested' where bank_txn_id = p_txn;
      return jsonb_build_object('suggested', r.rule_code, 'count', jsonb_array_length(v_sets));
    end if;
  end loop;

  update bank_transactions set recon_status = 'unreconciled' where bank_txn_id = p_txn and recon_status = 'suggested';
  return jsonb_build_object('no_match', true);
end $$;

-- ---------------------------------------------------------------- Rule Book hook: reconcile first, book only what is left
create or replace function jr_process_bank_txn(p_txn_id uuid) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  t bank_transactions%rowtype; v_ctx jsonb; v_res jsonb; v_item jsonb; v_rec jsonb;
begin
  select * into t from bank_transactions where bank_txn_id = p_txn_id;
  if not found or t.match_status <> 'unmatched' then return jsonb_build_object('skipped', 'not an unmatched line'); end if;
  if t.recon_status in ('reconciled', 'excluded') then return jsonb_build_object('skipped', 'already ' || t.recon_status); end if;

  -- 1. is it already in the books? (or should it be kept out of them?)
  v_rec := br_apply_rules_to_txn(p_txn_id);
  select * into t from bank_transactions where bank_txn_id = p_txn_id;
  if t.recon_status in ('reconciled', 'excluded', 'suggested') then
    return jsonb_build_object('reconciliation', v_rec);
  end if;

  -- 2. not in the books: let the Rule Book book it
  v_ctx := jsonb_build_object(
    'description', coalesce(t.reference, ''), 'amount', t.amount, 'direction', t.type, 'date', t.txn_date,
    'bank_account_id', t.bank_account_id,
    'bank_account', (select bank_name from bank_accounts where bank_account_id = t.bank_account_id));
  v_res := jr_fire('bank.' || t.type, 'bank_txn', t.bank_txn_id, v_ctx, 'bank:' || t.bank_txn_id);
  for v_item in select * from jsonb_array_elements(coalesce(v_res -> 'results', '[]'::jsonb)) loop
    update bank_transactions
       set matched_entity = 'journal_rule', matched_reference_id = (v_item ->> 'voucher_id')::uuid,
           match_status = case when v_item ->> 'status' = 'posted' then 'matched' else 'partial' end
     where bank_txn_id = p_txn_id;
    if v_item ->> 'status' = 'posted' then
      perform br_link_rule_voucher(p_txn_id, (v_item ->> 'voucher_id')::uuid);
    end if;
  end loop;
  return v_res;
end $$;

-- approving / discarding a rule draft now keeps reconciliation in step
create or replace function approve_rule_voucher(p_voucher_id uuid) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
declare bt record;
begin
  if not has_accounting_write() then raise exception 'Not authorized to approve vouchers'; end if;
  if not exists (select 1 from vouchers where voucher_id = p_voucher_id and status = 'draft') then
    raise exception 'Only a draft voucher can be approved';
  end if;
  if exists (select 1 from bank_transactions where matched_entity = 'journal_rule' and matched_reference_id = p_voucher_id and recon_status = 'suggested') then
    raise exception 'A reconciliation suggestion is still open for this bank line - accept or reject it first, so the entry is not booked twice';
  end if;
  update vouchers set status = 'posted', approved_by = auth.uid() where voucher_id = p_voucher_id;
  update journal_rule_log set status = 'posted' where voucher_id = p_voucher_id and status = 'draft';
  update credit_notes set status = 'posted' where voucher_id = p_voucher_id and status = 'draft';
  update bank_transactions set match_status = 'matched'
   where matched_entity = 'journal_rule' and matched_reference_id = p_voucher_id;
  for bt in select bank_txn_id from bank_transactions where matched_entity = 'journal_rule' and matched_reference_id = p_voucher_id loop
    perform br_link_rule_voucher(bt.bank_txn_id, p_voucher_id);
  end loop;
end $$;

-- ---------------------------------------------------------------- statement ingestion (API / CSV / typed)
create or replace function br_ingest(p_bank_account_id uuid, p_lines jsonb, p_source text) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  ln jsonb; v_date date; v_amt numeric; v_type text; v_desc text; v_ext text; v_bal numeric; v_val date; v_hash text;
  v_ins int := 0; v_dup int := 0; v_bad int := 0; v_errs jsonb := '[]'::jsonb; v_idx int := 0; v_id uuid; v_ids uuid[] := '{}';
  v_seen jsonb := '{}'::jsonb; v_occ int; v_key text;
  v_rec int; v_sug int; v_exc int; v_booked int; v_open int; v_drafts int;
begin
  if not exists (select 1 from bank_accounts where bank_account_id = p_bank_account_id) then raise exception 'Unknown bank account'; end if;
  if jsonb_typeof(p_lines) <> 'array' then raise exception 'Expected a list of statement lines'; end if;
  if jsonb_array_length(p_lines) > 5000 then raise exception 'Send at most 5000 lines at a time'; end if;

  for ln in select * from jsonb_array_elements(p_lines) loop
    v_idx := v_idx + 1;
    begin
      v_date := coalesce(nullif(ln ->> 'date', ''), nullif(ln ->> 'txn_date', ''))::date;
      v_val  := nullif(ln ->> 'value_date', '')::date;
      v_amt  := nullif(replace(coalesce(ln ->> 'amount', ''), ',', ''), '')::numeric;
      v_type := lower(coalesce(ln ->> 'type', ''));
      if v_amt is null and ln ? 'debit' and coalesce(nullif(replace(ln ->> 'debit', ',', ''), '')::numeric, 0) > 0 then
        v_amt := replace(ln ->> 'debit', ',', '')::numeric; v_type := 'debit';
      elsif v_amt is null and ln ? 'credit' and coalesce(nullif(replace(ln ->> 'credit', ',', ''), '')::numeric, 0) > 0 then
        v_amt := replace(ln ->> 'credit', ',', '')::numeric; v_type := 'credit';
      end if;
      if v_amt is null then raise exception 'no amount'; end if;
      if v_type not in ('credit', 'debit') then v_type := case when v_amt < 0 then 'debit' else 'credit' end; end if;
      v_amt := abs(v_amt);
      if v_date is null then raise exception 'no date'; end if;
      if v_amt < 0.005 then raise exception 'zero amount'; end if;
      v_desc := btrim(coalesce(ln ->> 'description', ln ->> 'reference', ln ->> 'narration', ''));
      v_ext  := nullif(btrim(coalesce(ln ->> 'external_id', ln ->> 'txn_id', '')), '');
      v_bal  := nullif(replace(coalesce(ln ->> 'balance', ''), ',', ''), '')::numeric;
      if v_ext is not null then
        v_hash := null;
      else
        v_key := concat_ws('|', p_bank_account_id, v_date, v_type, v_amt, upper(v_desc), coalesce(v_bal::text, ''));
        v_occ := coalesce((v_seen ->> v_key)::int, 0) + 1;
        v_seen := v_seen || jsonb_build_object(v_key, v_occ);
        v_hash := md5(v_key || '|' || v_occ);
      end if;
      insert into bank_transactions (bank_account_id, txn_date, reference, amount, type, external_txn_id, value_date, balance, source, line_hash, raw)
      values (p_bank_account_id, v_date, nullif(v_desc, ''), v_amt, v_type, v_ext, v_val, v_bal, p_source, v_hash, ln)
      on conflict do nothing
      returning bank_txn_id into v_id;
      if v_id is null then v_dup := v_dup + 1; else v_ins := v_ins + 1; v_ids := v_ids || v_id; end if;
      v_id := null;
    exception when others then
      v_bad := v_bad + 1;
      if jsonb_array_length(v_errs) < 20 then v_errs := v_errs || jsonb_build_array(jsonb_build_object('row', v_idx, 'problem', sqlerrm)); end if;
    end;
  end loop;

  select count(*) filter (where matched_entity = 'journal_rule' and match_status = 'partial') into v_drafts
    from bank_transactions where bank_txn_id = any (v_ids);
  select count(*) filter (where recon_status = 'reconciled' and match_status = 'matched' and matched_entity = 'book_entry'),
         count(*) filter (where recon_status = 'suggested'),
         count(*) filter (where recon_status = 'excluded'),
         count(*) filter (where matched_entity = 'journal_rule' and match_status = 'matched'),
         count(*) filter (where recon_status = 'unreconciled' and matched_entity is distinct from 'journal_rule')
    into v_rec, v_sug, v_exc, v_booked, v_open
    from bank_transactions where bank_txn_id = any (v_ids);

  insert into bank_feeds (bank_account_id, provider, last_synced_at, last_status, last_message)
  values (p_bank_account_id, case when p_source = 'api' then 'api_push' when p_source = 'csv' then 'csv' else 'manual' end, now(),
          case when v_bad > 0 then 'partial' else 'ok' end, v_ins || ' new, ' || v_dup || ' already imported, ' || v_bad || ' rejected')
  on conflict (bank_account_id) do update
    set last_synced_at = now(), last_status = excluded.last_status, last_message = excluded.last_message;

  return jsonb_build_object('received', v_idx, 'imported', v_ins, 'duplicates_skipped', v_dup, 'rejected', v_bad, 'problems', v_errs,
                            'matched_to_books', v_rec, 'suggested', v_sug, 'excluded', v_exc, 'booked_by_rules', v_booked, 'sent_for_review', v_drafts, 'needs_attention', v_open);
end $$;

create or replace function ingest_bank_statement(p_bank_account_id uuid, p_lines jsonb, p_source text default 'csv') returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not has_bankcod_write() then raise exception 'Not authorized to import bank statements'; end if;
  return br_ingest(p_bank_account_id, p_lines, case when p_source in ('csv', 'manual', 'api') then p_source else 'csv' end);
end $$;

-- called only by the bank-statement-sync Edge Function (service role)
create or replace function ingest_bank_statement_service(p_bank_account_id uuid, p_lines jsonb) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  return br_ingest(p_bank_account_id, p_lines, 'api');
end $$;

create or replace function bank_feed_for_sync(p_bank_account_id uuid) returns jsonb
language sql stable security definer set search_path = public, pg_temp as $$
  select to_jsonb(f) from bank_feeds f where f.bank_account_id = p_bank_account_id
$$;

create or replace function bank_feed_mark(p_bank_account_id uuid, p_status text, p_message text) returns void
language sql security definer set search_path = public, pg_temp as $$
  insert into bank_feeds (bank_account_id, last_synced_at, last_status, last_message) values (p_bank_account_id, now(), p_status, left(p_message, 500))
  on conflict (bank_account_id) do update set last_synced_at = now(), last_status = p_status, last_message = left(p_message, 500)
$$;

-- ---------------------------------------------------------------- human overrides
create or replace function br_match_manual(p_txn uuid, p_line_ids uuid[], p_note text default null, p_allow_difference boolean default false) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare t bank_transactions%rowtype; v_ledger uuid; v_sum numeric; l uuid; v_row record; v_diff numeric;
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  select * into t from bank_transactions where bank_txn_id = p_txn;
  if not found then raise exception 'Statement line not found'; end if;
  if p_line_ids is null or cardinality(p_line_ids) = 0 then raise exception 'Choose at least one book entry'; end if;
  if exists (select 1 from bank_recon_matches where bank_txn_id = p_txn and status = 'active' and method = 'rule_booked') then
    raise exception 'This line was booked from the statement by a rule. To change it, exclude the line and reverse the entry, or discard the draft.';
  end if;
  v_ledger := br_bank_ledger_of(t.bank_account_id);

  v_sum := 0;
  foreach l in array p_line_ids loop
    select vl.*, v.status as vstatus, v.voucher_no into v_row
      from voucher_lines vl join vouchers v on v.voucher_id = vl.voucher_id where vl.voucher_line_id = l;
    if not found then raise exception 'Book entry not found'; end if;
    if v_row.vstatus <> 'posted' then raise exception 'Voucher % is not posted yet', v_row.voucher_no; end if;
    if v_row.ledger_id <> v_ledger then raise exception 'Voucher % is not on this bank account''s ledger', v_row.voucher_no; end if;
    if (t.type = 'credit' and v_row.debit <= 0) or (t.type = 'debit' and v_row.credit <= 0) then
      raise exception 'Voucher % is on the wrong side (money %)', v_row.voucher_no, case when t.type = 'credit' then 'in' else 'out' end;
    end if;
    if exists (select 1 from bank_recon_matches m where m.voucher_line_id = l and m.status = 'active' and m.bank_txn_id <> p_txn) then
      raise exception 'Voucher % is already matched to another statement line - unmatch that one first', v_row.voucher_no;
    end if;
    v_sum := v_sum + case when t.type = 'credit' then v_row.debit else v_row.credit end;
  end loop;

  v_diff := t.amount - v_sum;
  if abs(v_diff) > 0.005 and not p_allow_difference then
    raise exception 'The chosen entries total % but the bank line is %. Tick "accept the difference" if that is intended.', v_sum, t.amount;
  end if;

  -- override: whatever was there before (rule match, old manual match, exclusion, rule draft) is replaced
  perform br_cancel_rule_draft(p_txn);
  perform br_unlink(p_txn);
  perform br_link(p_txn, p_line_ids, 'manual', null,
                  coalesce(p_note, '') || case when abs(v_diff) > 0.005 then ' [difference accepted: ' || v_diff || ']' else '' end);
  return jsonb_build_object('reconciled', true, 'difference', v_diff);
end $$;

create or replace function br_unmatch(p_txn uuid) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  if exists (select 1 from bank_recon_matches where bank_txn_id = p_txn and status = 'active' and method = 'rule_booked') then
    raise exception 'This line was booked from the statement by a rule, so it cannot simply be unmatched. Exclude it and reverse the entry instead.';
  end if;
  perform br_unlink(p_txn);
end $$;

create or replace function br_exclude_txn(p_txn uuid, p_reason text, p_note text default null, p_reverse boolean default false) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare t bank_transactions%rowtype; v_v vouchers%rowtype; v_rev uuid;
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  if p_reason not in ('duplicate_import', 'own_transfer', 'not_business', 'other') then raise exception 'Unknown exclusion reason'; end if;
  select * into t from bank_transactions where bank_txn_id = p_txn;
  if not found then raise exception 'Statement line not found'; end if;

  -- a voucher the Rule Book made from this very line
  if t.matched_entity = 'journal_rule' and t.matched_reference_id is not null then
    select * into v_v from vouchers where voucher_id = t.matched_reference_id;
    if found and v_v.status = 'draft' then
      perform br_cancel_rule_draft(p_txn);
    elsif found and v_v.status = 'posted' then
      if not p_reverse then
        raise exception 'A rule already posted voucher % for this line. Excluding it means reversing that voucher - choose "also reverse the entry".', v_v.voucher_no;
      end if;
      v_rev := br_reverse_voucher(v_v.voucher_id, 'bank line excluded: ' || p_reason);
      update journal_rule_log set status = 'discarded', message = coalesce(message, '') || ' (reversed by ' || (select voucher_no from vouchers where voucher_id = v_rev) || ')'
       where voucher_id = v_v.voucher_id and status = 'posted';
      update bank_recon_matches set status = 'undone', undone_by = auth.uid(), undone_at = now()
       where bank_txn_id = p_txn and status = 'active';
      -- the original and its reversal cancel each other; neither belongs in reconciliation any more
      insert into bank_recon_book_exclusions (voucher_line_id, reason, excluded_by)
      select vl.voucher_line_id, 'Reversed: bank line excluded (' || p_reason || ')', auth.uid()
        from voucher_lines vl where vl.voucher_id in (v_v.voucher_id, v_rev) and vl.ledger_id = br_bank_ledger_of(t.bank_account_id)
      on conflict (voucher_line_id) do nothing;
    end if;
  end if;

  perform br_unlink(p_txn);
  update bank_recon_suggestions set status = 'withdrawn', decided_by = auth.uid(), decided_at = now() where bank_txn_id = p_txn and status = 'pending';
  update bank_transactions
     set recon_status = 'excluded', match_status = 'matched', matched_entity = 'excluded', matched_reference_id = null,
         excluded_reason = p_reason, excluded_by = auth.uid(), excluded_at = now(), recon_note = p_note
   where bank_txn_id = p_txn;
  return jsonb_build_object('excluded', true, 'reversal_voucher_id', v_rev);
end $$;

create or replace function br_include_txn(p_txn uuid) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  if not exists (select 1 from bank_transactions where bank_txn_id = p_txn and recon_status = 'excluded') then
    raise exception 'This line is not excluded';
  end if;
  update bank_transactions
     set recon_status = 'unreconciled', match_status = 'unmatched', matched_entity = null, matched_reference_id = null,
         excluded_reason = null, excluded_by = null, excluded_at = null, recon_note = null
   where bank_txn_id = p_txn;
  return jsonb_build_object('included', true, 'result', jr_process_bank_txn(p_txn));
end $$;

create or replace function br_accept_suggestion(p_suggestion uuid) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare s bank_recon_suggestions%rowtype;
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  select * into s from bank_recon_suggestions where suggestion_id = p_suggestion and status = 'pending';
  if not found then raise exception 'This suggestion is no longer available'; end if;
  return br_match_manual(s.bank_txn_id, s.voucher_line_ids, 'Accepted suggestion from rule ' || coalesce(s.recon_rule_code, ''), true);
end $$;

-- "Not a match": keep it out of future proposals and let the Rule Book book it as a fresh entry
create or replace function br_reject_suggestion(p_suggestion uuid, p_book_it boolean default true) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare s bank_recon_suggestions%rowtype; v_left int; v_res jsonb;
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  select * into s from bank_recon_suggestions where suggestion_id = p_suggestion and status = 'pending';
  if not found then raise exception 'This suggestion is no longer available'; end if;
  update bank_recon_suggestions set status = 'rejected', decided_by = auth.uid(), decided_at = now() where suggestion_id = p_suggestion;
  select count(*) into v_left from bank_recon_suggestions where bank_txn_id = s.bank_txn_id and status = 'pending';
  if v_left = 0 then
    update bank_transactions set recon_status = 'unreconciled' where bank_txn_id = s.bank_txn_id and recon_status = 'suggested';
    if p_book_it then v_res := jr_process_bank_txn(s.bank_txn_id); end if;
  end if;
  return jsonb_build_object('rejected', true, 'remaining', v_left, 'result', v_res);
end $$;

-- Book a missing entry straight from a statement line (e.g. a payment nobody had recorded).
create or replace function br_book_txn(p_txn uuid, p_ledger uuid, p_narration text default null) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  t bank_transactions%rowtype; v_bank uuid; v_period uuid; v_vt uuid; v_prefix text; v_no text; v_vid uuid; v_line uuid;
begin
  if not has_accounting_write() then raise exception 'Not authorized to post vouchers'; end if;
  select * into t from bank_transactions where bank_txn_id = p_txn;
  if not found then raise exception 'Statement line not found'; end if;
  if t.recon_status = 'reconciled' then raise exception 'This line is already reconciled'; end if;
  v_bank := br_bank_ledger_of(t.bank_account_id);
  if v_bank is null then raise exception 'This bank account has no ledger'; end if;
  if p_ledger = v_bank then raise exception 'Choose the other side of the entry, not the bank itself'; end if;
  if not exists (select 1 from ledgers where ledger_id = p_ledger and status = 'active') then raise exception 'Choose an active account'; end if;
  select accounting_period_id into v_period from accounting_periods where t.txn_date between start_date and end_date and status = 'open' limit 1;
  if v_period is null then raise exception 'No open accounting period covers %', t.txn_date; end if;
  select voucher_type_id, numbering_prefix into v_vt, v_prefix from voucher_types where code = case when t.type = 'credit' then 'RECEIPT' else 'PAYMENT' end;
  v_no := v_prefix || '-' || to_char(t.txn_date, 'YYMM') || '-' || lpad(nextval('journal_voucher_seq')::text, 6, '0');

  -- a previous draft from the rules for this line is replaced by this explicit entry
  perform br_cancel_rule_draft(p_txn);
  perform br_unlink(p_txn);
  update bank_recon_suggestions set status = 'withdrawn' where bank_txn_id = p_txn and status = 'pending';

  insert into vouchers (voucher_type_id, voucher_no, voucher_date, accounting_period_id, status, source_type, source_id, narration, total_debit, total_credit, created_by)
  values (v_vt, v_no, t.txn_date, v_period, 'draft', 'bank_txn', t.bank_txn_id, coalesce(nullif(p_narration, ''), t.reference, 'Bank entry'), t.amount, t.amount, auth.uid())
  returning voucher_id into v_vid;
  insert into voucher_lines (voucher_id, ledger_id, debit, credit, reference_type, reference_id, narration) values
    (v_vid, case when t.type = 'credit' then v_bank else p_ledger end, t.amount, 0, 'bank_txn', t.bank_txn_id, t.reference),
    (v_vid, case when t.type = 'credit' then p_ledger else v_bank end, 0, t.amount, 'bank_txn', t.bank_txn_id, t.reference);
  update vouchers set status = 'posted', approved_by = auth.uid() where voucher_id = v_vid;
  update bank_transactions set matched_entity = 'journal_rule', matched_reference_id = v_vid, match_status = 'matched' where bank_txn_id = p_txn;
  perform br_link_rule_voucher(p_txn, v_vid);
  return jsonb_build_object('voucher_id', v_vid, 'voucher_no', v_no);
end $$;

create or replace function br_exclude_book_line(p_voucher_line_id uuid, p_reason text) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  if coalesce(btrim(p_reason), '') = '' then raise exception 'Say why this entry is set aside'; end if;
  if exists (select 1 from bank_recon_matches where voucher_line_id = p_voucher_line_id and status = 'active') then
    raise exception 'This entry is matched to a statement line - unmatch it first';
  end if;
  insert into bank_recon_book_exclusions (voucher_line_id, reason, excluded_by) values (p_voucher_line_id, p_reason, auth.uid())
  on conflict (voucher_line_id) do update set reason = excluded.reason, excluded_by = excluded.excluded_by, excluded_at = now();
end $$;

create or replace function br_include_book_line(p_voucher_line_id uuid) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  delete from bank_recon_book_exclusions where voucher_line_id = p_voucher_line_id;
end $$;

-- "Match with books" button: tries the match rules only (never books anything new)
create or replace function run_bank_reconciliation(p_bank_account_id uuid default null) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare t record; v_res jsonb; v_n int := 0; v_rec int := 0; v_sug int := 0; v_exc int := 0; v_draft boolean;
begin
  if not has_bankcod_write() then raise exception 'Not authorized to reconcile'; end if;
  for t in select bank_txn_id, (match_status = 'partial' and matched_entity = 'journal_rule') as has_draft from bank_transactions
            where recon_status in ('unreconciled', 'suggested') and (p_bank_account_id is null or bank_account_id = p_bank_account_id)
              and (match_status = 'unmatched' or (match_status = 'partial' and matched_entity = 'journal_rule'))
            order by txn_date, created_at loop
    v_n := v_n + 1;
    v_draft := t.has_draft;
    if v_draft then perform br_cancel_rule_draft(t.bank_txn_id); end if;
    v_res := br_apply_rules_to_txn(t.bank_txn_id);
    if v_res ? 'reconciled' then v_rec := v_rec + 1;
    elsif v_res ? 'suggested' then v_sug := v_sug + 1;
    elsif v_res ? 'excluded' then v_exc := v_exc + 1;
    elsif v_draft then perform jr_process_bank_txn(t.bank_txn_id);   -- nothing in the books: put the rule's draft back
    end if;
  end loop;
  return jsonb_build_object('checked', v_n, 'reconciled', v_rec, 'suggested', v_sug, 'excluded', v_exc);
end $$;

-- ---------------------------------------------------------------- screens: data for the reconciliation page
create or replace function bank_recon_lines(p_bank_account_id uuid, p_status text default null, p_limit int default 300)
returns table (bank_txn_id uuid, txn_date date, description text, amount numeric, type text, balance numeric, source text,
               recon_status text, match_status text, matched_entity text, excluded_reason text, recon_note text,
               matches jsonb, suggestions jsonb, draft_voucher jsonb)
language plpgsql stable security definer set search_path = public, pg_temp as $$
begin
  if not has_bankcod_view() then raise exception 'Not authorized'; end if;
  return query
  select b.bank_txn_id, b.txn_date, b.reference, b.amount, b.type, b.balance, b.source, b.recon_status, b.match_status, b.matched_entity,
         b.excluded_reason, b.recon_note,
         coalesce((select jsonb_agg(jsonb_build_object('voucher_no', v.voucher_no, 'voucher_date', v.voucher_date, 'amount', m.amount,
                                                       'method', m.method, 'rule', m.recon_rule_code, 'narration', coalesce(vl.narration, v.narration))
                                    order by v.voucher_date)
                     from bank_recon_matches m join voucher_lines vl on vl.voucher_line_id = m.voucher_line_id
                     join vouchers v on v.voucher_id = vl.voucher_id
                    where m.bank_txn_id = b.bank_txn_id and m.status = 'active'), '[]'::jsonb),
         coalesce((select jsonb_agg(jsonb_build_object('suggestion_id', s.suggestion_id, 'rule', s.recon_rule_code, 'score', s.score,
                      'lines', (select jsonb_agg(jsonb_build_object('voucher_no', v.voucher_no, 'voucher_date', v.voucher_date,
                                  'amount', case when b.type = 'credit' then vl.debit else vl.credit end, 'narration', coalesce(vl.narration, v.narration)))
                                  from voucher_lines vl join vouchers v on v.voucher_id = vl.voucher_id where vl.voucher_line_id = any (s.voucher_line_ids)))
                    order by s.score desc)
                     from bank_recon_suggestions s where s.bank_txn_id = b.bank_txn_id and s.status = 'pending'), '[]'::jsonb),
         (select jsonb_build_object('voucher_id', v.voucher_id, 'voucher_no', v.voucher_no, 'status', v.status)
            from vouchers v where v.voucher_id = b.matched_reference_id and b.matched_entity = 'journal_rule' and v.status = 'draft')
    from bank_transactions b
   where b.bank_account_id = p_bank_account_id
     and (p_status is null or b.recon_status = p_status or (p_status = 'open' and b.recon_status in ('unreconciled', 'suggested')))
   order by b.txn_date desc, b.created_at desc
   limit least(coalesce(p_limit, 300), 1000);
end $$;

create or replace function bank_recon_book_lines(p_bank_account_id uuid, p_which text default 'open')
returns table (voucher_line_id uuid, voucher_no text, voucher_date date, direction text, amount numeric, narration text, source_type text,
               matched boolean, excluded boolean, excluded_reason text)
language plpgsql stable security definer set search_path = public, pg_temp as $$
declare v_ledger uuid;
begin
  if not has_bankcod_view() then raise exception 'Not authorized'; end if;
  v_ledger := br_bank_ledger_of(p_bank_account_id);
  return query
  select vl.voucher_line_id, v.voucher_no, v.voucher_date, (case when vl.debit > 0 then 'in' else 'out' end)::text,
         (case when vl.debit > 0 then vl.debit else vl.credit end)::numeric, coalesce(vl.narration, v.narration), v.source_type,
         exists (select 1 from bank_recon_matches m where m.voucher_line_id = vl.voucher_line_id and m.status = 'active'),
         x.voucher_line_id is not null, x.reason
    from voucher_lines vl join vouchers v on v.voucher_id = vl.voucher_id
    left join bank_recon_book_exclusions x on x.voucher_line_id = vl.voucher_line_id
   where vl.ledger_id = v_ledger and v.status = 'posted'
     and (p_which = 'all'
          or (p_which = 'open' and not exists (select 1 from bank_recon_matches m where m.voucher_line_id = vl.voucher_line_id and m.status = 'active')))
   order by v.voucher_date desc, v.voucher_no desc
   limit 500;
end $$;

-- every posted entry the user could pair with this statement line (for the "match by hand" picker)
create or replace function bank_recon_candidates_for_txn(p_txn uuid, p_window int default 30)
returns table (voucher_line_id uuid, voucher_no text, voucher_date date, amount numeric, narration text, source_type text, day_gap int)
language plpgsql stable security definer set search_path = public, pg_temp as $$
begin
  if not has_bankcod_view() then raise exception 'Not authorized'; end if;
  return query
  select c.voucher_line_id, c.voucher_no, c.voucher_date, c.amount, c.narration, c.source_type, c.day_gap
    from br_candidates(p_txn, least(coalesce(p_window, 30), 365)) c
   order by c.day_gap, c.voucher_date limit 200;
end $$;

-- the reconciliation statement: how the bank book and the bank statement tie together
create or replace function bank_recon_summary(p_bank_account_id uuid) returns jsonb
language plpgsql stable security definer set search_path = public, pg_temp as $$
declare
  v_ledger uuid; v_lg ledgers%rowtype; v_feed bank_feeds%rowtype;
  v_open_b numeric := 0; v_book numeric; v_open_s numeric := 0; v_stmt numeric;
  v_bo_cr numeric; v_bo_db numeric; v_set_cr numeric; v_set_db numeric; v_bk_in numeric; v_bk_out numeric; v_bx_in numeric; v_bx_out numeric;
  v_diffs numeric; v_expected numeric; v_reported numeric; v_reported_date date; v_computed_at_reported numeric; v_seq bigint;
  v_counts jsonb;
begin
  if not has_bankcod_view() then raise exception 'Not authorized'; end if;
  v_ledger := br_bank_ledger_of(p_bank_account_id);
  if v_ledger is null then raise exception 'This bank account has no ledger'; end if;
  select * into v_lg from ledgers where ledger_id = v_ledger;
  select * into v_feed from bank_feeds where bank_account_id = p_bank_account_id;
  v_open_b := case when v_lg.opening_balance_type = 'credit' then -v_lg.opening_balance else v_lg.opening_balance end;
  v_open_s := coalesce(v_feed.statement_opening_balance, 0);

  select v_open_b + coalesce(sum(vl.debit - vl.credit), 0) into v_book
    from voucher_lines vl join vouchers v on v.voucher_id = vl.voucher_id where vl.ledger_id = v_ledger and v.status = 'posted';

  select v_open_s + coalesce(sum(case when type = 'credit' then amount else -amount end), 0) into v_stmt
    from bank_transactions where bank_account_id = p_bank_account_id and coalesce(excluded_reason, '') <> 'duplicate_import';

  select coalesce(sum(amount) filter (where type = 'credit'), 0), coalesce(sum(amount) filter (where type = 'debit'), 0) into v_bo_cr, v_bo_db
    from bank_transactions where bank_account_id = p_bank_account_id and recon_status in ('unreconciled', 'suggested');
  select coalesce(sum(amount) filter (where type = 'credit'), 0), coalesce(sum(amount) filter (where type = 'debit'), 0) into v_set_cr, v_set_db
    from bank_transactions where bank_account_id = p_bank_account_id and recon_status = 'excluded' and coalesce(excluded_reason, '') <> 'duplicate_import';

  select coalesce(sum(vl.debit) filter (where x.voucher_line_id is null), 0), coalesce(sum(vl.credit) filter (where x.voucher_line_id is null), 0),
         coalesce(sum(vl.debit) filter (where x.voucher_line_id is not null), 0), coalesce(sum(vl.credit) filter (where x.voucher_line_id is not null), 0)
    into v_bk_in, v_bk_out, v_bx_in, v_bx_out
    from voucher_lines vl join vouchers v on v.voucher_id = vl.voucher_id
    left join bank_recon_book_exclusions x on x.voucher_line_id = vl.voucher_line_id
   where vl.ledger_id = v_ledger and v.status = 'posted'
     and not exists (select 1 from bank_recon_matches m where m.voucher_line_id = vl.voucher_line_id and m.status = 'active');

  -- differences the user chose to accept on matched lines (bank amount vs book amount)
  select coalesce(sum((case when b.type = 'credit' then 1 else -1 end) * (b.amount - coalesce(ms.amt, 0))), 0) into v_diffs
    from bank_transactions b
    left join (select bank_txn_id, sum(amount) amt from bank_recon_matches where status = 'active' group by bank_txn_id) ms on ms.bank_txn_id = b.bank_txn_id
   where b.bank_account_id = p_bank_account_id and b.recon_status = 'reconciled';

  v_expected := v_book + v_bo_cr - v_bo_db + v_set_cr - v_set_db - v_bk_in + v_bk_out - v_bx_in + v_bx_out + v_diffs + (v_open_s - v_open_b);

  -- the bank's own running balance on the last imported line vs what the imported lines add up to (spots missing lines in the feed)
  select balance, txn_date, import_seq into v_reported, v_reported_date, v_seq from bank_transactions
   where bank_account_id = p_bank_account_id and balance is not null order by import_seq desc limit 1;
  if v_reported is not null then
    select v_open_s + coalesce(sum(case when type = 'credit' then amount else -amount end), 0) into v_computed_at_reported
      from bank_transactions where bank_account_id = p_bank_account_id and import_seq <= v_seq and coalesce(excluded_reason, '') <> 'duplicate_import';
  end if;

  select jsonb_build_object(
      'statement_lines', count(*), 'reconciled', count(*) filter (where recon_status = 'reconciled'),
      'suggested', count(*) filter (where recon_status = 'suggested'), 'unreconciled', count(*) filter (where recon_status = 'unreconciled'),
      'excluded', count(*) filter (where recon_status = 'excluded'))
    into v_counts from bank_transactions where bank_account_id = p_bank_account_id;

  return jsonb_build_object(
    'ledger', v_lg.name,
    'book_balance', v_book,
    'statement_balance', v_stmt,
    'difference', v_stmt - v_book,
    'in_bank_not_in_books', jsonb_build_object('money_in', v_bo_cr, 'money_out', v_bo_db),
    'set_aside_by_you', jsonb_build_object('money_in', v_set_cr, 'money_out', v_set_db),
    'in_books_not_in_bank', jsonb_build_object('money_in', v_bk_in, 'money_out', v_bk_out),
    'books_entries_set_aside', jsonb_build_object('money_in', v_bx_in, 'money_out', v_bx_out),
    'accepted_differences', v_diffs,
    'opening_gap', v_open_s - v_open_b,
    'unexplained', round(v_stmt - v_expected, 2),
    'bank_reported_balance', v_reported, 'bank_reported_on', v_reported_date,
    'feed_gap', case when v_reported is null then null else round(v_reported - v_computed_at_reported, 2) end,
    'counts', v_counts);
end $$;

-- ---------------------------------------------------------------- admin: match rules + feed settings
create or replace function save_bank_recon_rule(p_rule jsonb) returns uuid
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_id uuid := nullif(p_rule ->> 'recon_rule_id', '')::uuid; v_action text := p_rule ->> 'action'; v_type text := coalesce(p_rule ->> 'match_type', 'one_to_one');
  v_src text[]; v_vt text[]; v_code text;
begin
  if not has_rulebook_edit() then raise exception 'Only a Super Admin or Finance Manager can change the matching rules'; end if;
  if coalesce(btrim(p_rule ->> 'name'), '') = '' then raise exception 'Rule name is required'; end if;
  if v_action not in ('auto_reconcile', 'suggest', 'exclude') then raise exception 'Choose what the rule should do'; end if;
  if v_action = 'exclude' and (coalesce(btrim(p_rule ->> 'keyword_value'), '') = '' or coalesce(p_rule ->> 'keyword_operator', '') = '') then
    raise exception 'An exclude rule must say which words in the bank narration to look for';
  end if;
  if v_type not in ('one_to_one', 'sum_of_entries') then raise exception 'Unknown match type'; end if;
  if jsonb_typeof(p_rule -> 'book_source_types') = 'array' then
    select nullif(array_agg(x), '{}') into v_src from jsonb_array_elements_text(p_rule -> 'book_source_types') x where btrim(x) <> '';
  end if;
  if jsonb_typeof(p_rule -> 'book_voucher_types') = 'array' then
    select nullif(array_agg(x), '{}') into v_vt from jsonb_array_elements_text(p_rule -> 'book_voucher_types') x where btrim(x) <> '';
  end if;

  if v_id is null then
    v_code := 'RC-C-' || lpad(nextval('journal_voucher_seq')::text, 4, '0');
    insert into bank_recon_rules (rule_code, name, description, priority, status, bank_account_id, direction, action, match_type, amount_tolerance, amount_tolerance_pct,
        date_window_days, reference_mode, keyword_operator, keyword_value, book_source_types, book_voucher_types, exclude_reason, updated_by)
    values (v_code, btrim(p_rule ->> 'name'), p_rule ->> 'description', coalesce((p_rule ->> 'priority')::int, 500), coalesce(p_rule ->> 'status', 'active'),
        nullif(p_rule ->> 'bank_account_id', '')::uuid, coalesce(p_rule ->> 'direction', 'any'), v_action, v_type,
        coalesce((p_rule ->> 'amount_tolerance')::numeric, 0), coalesce((p_rule ->> 'amount_tolerance_pct')::numeric, 0),
        coalesce((p_rule ->> 'date_window_days')::int, 3), coalesce(p_rule ->> 'reference_mode', 'ignore'),
        nullif(p_rule ->> 'keyword_operator', ''), nullif(p_rule ->> 'keyword_value', ''), v_src, v_vt,
        case when v_action = 'exclude' then coalesce(nullif(p_rule ->> 'exclude_reason', ''), 'other') end, auth.uid())
    returning recon_rule_id into v_id;
  else
    update bank_recon_rules set name = btrim(p_rule ->> 'name'), description = p_rule ->> 'description',
        priority = coalesce((p_rule ->> 'priority')::int, priority), status = coalesce(p_rule ->> 'status', status),
        bank_account_id = nullif(p_rule ->> 'bank_account_id', '')::uuid, direction = coalesce(p_rule ->> 'direction', 'any'),
        action = v_action, match_type = v_type, amount_tolerance = coalesce((p_rule ->> 'amount_tolerance')::numeric, 0),
        amount_tolerance_pct = coalesce((p_rule ->> 'amount_tolerance_pct')::numeric, 0),
        date_window_days = coalesce((p_rule ->> 'date_window_days')::int, 3), reference_mode = coalesce(p_rule ->> 'reference_mode', 'ignore'),
        keyword_operator = nullif(p_rule ->> 'keyword_operator', ''), keyword_value = nullif(p_rule ->> 'keyword_value', ''),
        book_source_types = v_src, book_voucher_types = v_vt,
        exclude_reason = case when v_action = 'exclude' then coalesce(nullif(p_rule ->> 'exclude_reason', ''), 'other') end,
        version = version + 1, updated_at = now(), updated_by = auth.uid()
     where recon_rule_id = v_id;
    if not found then raise exception 'Rule not found'; end if;
  end if;
  return v_id;
end $$;

create or replace function set_bank_recon_rule_status(p_rule_id uuid, p_status text) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not has_rulebook_edit() then raise exception 'Only a Super Admin or Finance Manager can change the matching rules'; end if;
  if p_status not in ('active', 'inactive') then raise exception 'Status must be active or inactive'; end if;
  update bank_recon_rules set status = p_status, version = version + 1, updated_at = now(), updated_by = auth.uid() where recon_rule_id = p_rule_id;
  if not found then raise exception 'Rule not found'; end if;
end $$;

create or replace function delete_bank_recon_rule(p_rule_id uuid) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not has_rulebook_edit() then raise exception 'Only a Super Admin or Finance Manager can change the matching rules'; end if;
  if exists (select 1 from bank_recon_rules where recon_rule_id = p_rule_id and is_system) then
    raise exception 'The accountant''s default rules can be switched off or edited, but not deleted';
  end if;
  delete from bank_recon_rules where recon_rule_id = p_rule_id;
end $$;

create or replace function reset_bank_recon_rule(p_rule_id uuid) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
declare d jsonb;
begin
  if not has_rulebook_edit() then raise exception 'Only a Super Admin or Finance Manager can change the matching rules'; end if;
  select default_definition into d from bank_recon_rules where recon_rule_id = p_rule_id and is_system;
  if d is null then raise exception 'Only the accountant''s default rules can be restored'; end if;
  update bank_recon_rules set
      name = d ->> 'name', description = d ->> 'description', priority = (d ->> 'priority')::int, status = d ->> 'status',
      bank_account_id = null, direction = d ->> 'direction', action = d ->> 'action', match_type = d ->> 'match_type',
      amount_tolerance = (d ->> 'amount_tolerance')::numeric, amount_tolerance_pct = (d ->> 'amount_tolerance_pct')::numeric,
      date_window_days = (d ->> 'date_window_days')::int, reference_mode = d ->> 'reference_mode',
      keyword_operator = d ->> 'keyword_operator', keyword_value = d ->> 'keyword_value',
      book_source_types = (select array_agg(x) from jsonb_array_elements_text(coalesce(d -> 'book_source_types', '[]'::jsonb)) x),
      book_voucher_types = null, exclude_reason = d ->> 'exclude_reason',
      version = version + 1, updated_at = now(), updated_by = auth.uid()
   where recon_rule_id = p_rule_id;
end $$;

create or replace function save_bank_feed(p_feed jsonb) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_acct uuid := (p_feed ->> 'bank_account_id')::uuid; v_url text := nullif(btrim(p_feed ->> 'endpoint_url'), '');
begin
  if not has_rulebook_edit() then raise exception 'Only a Super Admin or Finance Manager can change the statement feed'; end if;
  if not exists (select 1 from bank_accounts where bank_account_id = v_acct) then raise exception 'Unknown bank account'; end if;
  if coalesce(p_feed ->> 'provider', 'manual') = 'api_pull' and (v_url is null or v_url !~* '^https://') then
    raise exception 'The bank API address must start with https://';
  end if;
  if p_feed ? 'secret_name' and coalesce(p_feed ->> 'secret_name', '') !~ '^[A-Z][A-Z0-9_]{2,60}$' and coalesce(p_feed ->> 'secret_name', '') <> '' then
    raise exception 'The secret name must be capital letters, digits and underscores, e.g. BANKFEED_HDFC_TOKEN';
  end if;
  insert into bank_feeds (bank_account_id, provider, enabled, endpoint_url, http_method, auth_header_name, secret_name, field_map, sync_from,
                          statement_opening_balance, updated_by, updated_at)
  values (v_acct, coalesce(p_feed ->> 'provider', 'manual'), coalesce((p_feed ->> 'enabled')::boolean, false), v_url,
          coalesce(p_feed ->> 'http_method', 'GET'), coalesce(nullif(p_feed ->> 'auth_header_name', ''), 'Authorization'),
          nullif(p_feed ->> 'secret_name', ''), coalesce(p_feed -> 'field_map', '{}'::jsonb), nullif(p_feed ->> 'sync_from', '')::date,
          coalesce((p_feed ->> 'statement_opening_balance')::numeric, 0), auth.uid(), now())
  on conflict (bank_account_id) do update set
      provider = excluded.provider, enabled = excluded.enabled, endpoint_url = excluded.endpoint_url, http_method = excluded.http_method,
      auth_header_name = excluded.auth_header_name, secret_name = excluded.secret_name, field_map = excluded.field_map,
      sync_from = excluded.sync_from, statement_opening_balance = excluded.statement_opening_balance,
      updated_by = excluded.updated_by, updated_at = now();
end $$;

-- ---------------------------------------------------------------- CA default match rules
insert into bank_recon_rules (rule_code, name, description, priority, status, is_system, direction, action, match_type, amount_tolerance, amount_tolerance_pct,
                              date_window_days, reference_mode, keyword_operator, keyword_value, book_source_types, exclude_reason)
values
 ('RC-REF-EXACT', 'Same amount and the bank narration quotes our reference', 'The statement narration contains the voucher number, settlement ID, order number or AWB of a book entry, and the amount agrees to the rupee. Safe to link without asking.', 10, 'active', true, 'any', 'auto_reconcile', 'one_to_one', 0, 0, 7, 'required', null, null, null, null),
 ('RC-SETTLEMENT-COD', 'Marketplace / courier payout equals a settlement or COD receipt', 'A credit that equals a posted settlement or COD remittance within 10 days. Linked automatically when only one entry fits; otherwise proposed.', 20, 'active', true, 'credit', 'auto_reconcile', 'one_to_one', 0, 0, 10, 'ignore', null, null, array['settlement','cod'], null),
 ('RC-EXACT-SAME-DAY', 'Same amount on the same day', 'One book entry with exactly the same amount and date. If two entries fit equally, it is proposed instead of linked.', 30, 'active', true, 'any', 'auto_reconcile', 'one_to_one', 0, 0, 0, 'ignore', null, null, null, null),
 ('RC-EXACT-3D', 'Same amount within 3 days', 'Cheques, NEFT and UPI often clear a day or two after the entry is made. Proposed for a human to confirm.', 40, 'active', true, 'any', 'suggest', 'one_to_one', 0, 0, 3, 'ignore', null, null, null, null),
 ('RC-ROUNDING', 'Within ₹1 or 0.1% (rounding, paise)', 'Catches rupee rounding and paise differences. Proposed, never automatic.', 50, 'active', true, 'any', 'suggest', 'one_to_one', 1, 0.1, 3, 'ignore', null, null, null, null),
 ('RC-SUM-OF-ENTRIES', 'Several entries paid as one bank credit/debit', 'Two to five book entries add up to one statement line (for example two settlements paid together).', 60, 'active', true, 'any', 'suggest', 'sum_of_entries', 0, 0, 3, 'ignore', null, null, null, null),
 ('RC-LATE-CLEAR', 'Same amount within 15 days (late clearing)', 'Slow-clearing cheques and delayed payouts. Proposed only.', 70, 'active', true, 'any', 'suggest', 'one_to_one', 0, 0, 15, 'ignore', null, null, null, null),
 ('RC-EXCL-OWN-TRANSFER', 'Transfers between our own bank accounts', 'Keeps own-account transfers out of the books. Switched OFF - turn it on after checking the keywords suit your bank narrations.', 90, 'inactive', true, 'any', 'exclude', 'one_to_one', 0, 0, 3, 'ignore', 'contains_any', 'SELF TRANSFER|OWN ACCOUNT|OWN A/C|INTERNAL TRANSFER', null, 'own_transfer')
on conflict (rule_code) do nothing;

update bank_recon_rules r set default_definition = jsonb_build_object(
    'name', r.name, 'description', r.description, 'priority', r.priority, 'status', r.status, 'direction', r.direction, 'action', r.action,
    'match_type', r.match_type, 'amount_tolerance', r.amount_tolerance, 'amount_tolerance_pct', r.amount_tolerance_pct,
    'date_window_days', r.date_window_days, 'reference_mode', r.reference_mode, 'keyword_operator', r.keyword_operator,
    'keyword_value', r.keyword_value, 'book_source_types', to_jsonb(coalesce(r.book_source_types, '{}')), 'exclude_reason', r.exclude_reason)
 where r.is_system and r.default_definition is null;

-- ---------------------------------------------------------------- tidy up lines that already existed before this migration
do $$
declare bt record;
begin
  for bt in select bank_txn_id, matched_reference_id from bank_transactions
             where matched_entity = 'journal_rule' and match_status = 'matched' and recon_status = 'unreconciled' loop
    begin
      perform br_link_rule_voucher(bt.bank_txn_id, bt.matched_reference_id);
    exception when others then null;
    end;
  end loop;
end $$;

-- A book entry posted after the statement was imported (a settlement reconciled later, a payment entered late) finds its bank line.
create or replace function trg_voucher_posted_recon() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
declare ln record; t record;
begin
  begin
    if new.status = 'posted' and old.status is distinct from 'posted' and coalesce(new.source_type, '') not in ('bank_txn', 'reversal') then
      for ln in select vl.ledger_id, vl.debit, vl.credit from voucher_lines vl
                 where vl.voucher_id = new.voucher_id and vl.ledger_id in (select ledger_id from bank_accounts where ledger_id is not null) loop
        for t in select b.bank_txn_id from bank_transactions b join bank_accounts a on a.bank_account_id = b.bank_account_id
                  where a.ledger_id = ln.ledger_id and b.recon_status in ('unreconciled', 'suggested')
                    and (b.match_status = 'unmatched' or (b.match_status = 'partial' and b.matched_entity = 'journal_rule'))
                    and b.type = case when ln.debit > 0 then 'credit' else 'debit' end
                    and abs(b.amount - greatest(ln.debit, ln.credit)) <= 1 and abs(b.txn_date - new.voucher_date) <= 15 loop
          perform br_apply_rules_to_txn(t.bank_txn_id);
        end loop;
      end loop;
    end if;
  exception when others then
    null;   -- reconciliation must never block posting
  end;
  return new;
end $$;
drop trigger if exists trg_voucher_posted_recon on vouchers;
create trigger trg_voucher_posted_recon after update of status on vouchers
  for each row execute function trg_voucher_posted_recon();
revoke execute on function trg_voucher_posted_recon() from public, anon, authenticated;

-- ---------------------------------------------------------------- grants
revoke execute on function br_norm(text), br_tokens(text, text, text, uuid), br_bank_ledger_of(uuid), br_candidates(uuid, int, text[], text[]),
  br_link(uuid, uuid[], text, text, text), br_link_rule_voucher(uuid, uuid), br_unlink(uuid), br_reverse_voucher(uuid, text), br_cancel_rule_draft(uuid),
  br_apply_rules_to_txn(uuid), br_ingest(uuid, jsonb, text), jr_process_bank_txn(uuid) from public, anon, authenticated;
revoke execute on function ingest_bank_statement(uuid, jsonb, text), br_match_manual(uuid, uuid[], text, boolean), br_unmatch(uuid),
  br_exclude_txn(uuid, text, text, boolean), br_include_txn(uuid), br_accept_suggestion(uuid), br_reject_suggestion(uuid, boolean),
  br_book_txn(uuid, uuid, text), br_exclude_book_line(uuid, text), br_include_book_line(uuid), run_bank_reconciliation(uuid),
  bank_recon_lines(uuid, text, int), bank_recon_book_lines(uuid, text), bank_recon_candidates_for_txn(uuid, int), bank_recon_summary(uuid),
  save_bank_recon_rule(jsonb), set_bank_recon_rule_status(uuid, text), delete_bank_recon_rule(uuid), reset_bank_recon_rule(uuid), save_bank_feed(jsonb),
  approve_rule_voucher(uuid) from public, anon;
grant execute on function ingest_bank_statement(uuid, jsonb, text), br_match_manual(uuid, uuid[], text, boolean), br_unmatch(uuid),
  br_exclude_txn(uuid, text, text, boolean), br_include_txn(uuid), br_accept_suggestion(uuid), br_reject_suggestion(uuid, boolean),
  br_book_txn(uuid, uuid, text), br_exclude_book_line(uuid, text), br_include_book_line(uuid), run_bank_reconciliation(uuid),
  bank_recon_lines(uuid, text, int), bank_recon_book_lines(uuid, text), bank_recon_candidates_for_txn(uuid, int), bank_recon_summary(uuid),
  save_bank_recon_rule(jsonb), set_bank_recon_rule_status(uuid, text), delete_bank_recon_rule(uuid), reset_bank_recon_rule(uuid), save_bank_feed(jsonb),
  approve_rule_voucher(uuid) to authenticated;
revoke execute on function ingest_bank_statement_service(uuid, jsonb), bank_feed_for_sync(uuid), bank_feed_mark(uuid, text, text) from public, anon, authenticated;
grant execute on function ingest_bank_statement_service(uuid, jsonb), bank_feed_for_sync(uuid), bank_feed_mark(uuid, text, text) to service_role;
